In [3]:
library(stringr)
sub <- function(x) {
  substr(x,3,6)  
}
lapply(names(precip), sub)# lapply using user def function
a <- array(1:18,dim=c(2,3,3))
a
lapply(list(c(1,2,3),c(23,45),matrix(1:12,2,6),a), sum) # lapply using the list which contains vector, matrix and array

############### tapply ####################
head(iris)
print(tapply(iris$Petal.Length,iris$Species,mean))
print(tapply(airquality$Ozone,airquality$Month,mean,na.rm=TRUE))
print(tapply(warpbreaks$breaks,warpbreaks$tension,sum))
############# aggregate
aggregate(iris[-5], list(iris$Species), mean)
aggregate(mtcars, list(mtcars$cyl), mean)
## Formulas, one ~ one, one ~ many, many ~ one, and many ~ many:
aggregate(weight ~ feed, data = chickwts, mean)
aggregate(breaks ~ wool + tension, data = warpbreaks, mean)
aggregate(cbind(Ozone, Temp) ~ Month, data = airquality, mean)
aggregate(cbind(ncases, ncontrols) ~ alcgp + tobgp, data = esoph, sum)

## Dot notation:
aggregate(. ~ Species, data = iris, mean)
aggregate(len ~ ., data = ToothGrowth, mean)

[[1]]
[1] "bile"

[[2]]
[1] "neau"

[[3]]
[1] "oeni"

[[4]]
[1] "ttle"

[[5]]
[1] "s An"

[[6]]
[1] "cram"

[[7]]
[1] "n Fr"

[[8]]
[1] "nver"

[[9]]
[1] "rtfo"

[[10]]
[1] "lmin"

[[11]]
[1] "shin"

[[12]]
[1] "ckso"

[[13]]
[1] "ami"

[[14]]
[1] "lant"

[[15]]
[1] "nolu"

[[16]]
[1] "ise"

[[17]]
[1] "icag"

[[18]]
[1] "oria"

[[19]]
[1] "dian"

[[20]]
[1] "s Mo"

[[21]]
[1] "chit"

[[22]]
[1] "uisv"

[[23]]
[1] "w Or"

[[24]]
[1] "rtla"

[[25]]
[1] "ltim"

[[26]]
[1] "ston"

[[27]]
[1] "troi"

[[28]]
[1] "ult "

[[29]]
[1] "luth"

[[30]]
[1] "nnea"

[[31]]
[1] "ckso"

[[32]]
[1] "nsas"

[[33]]
[1] " Lou"

[[34]]
[1] "eat "

[[35]]
[1] "aha"

[[36]]
[1] "no"

[[37]]
[1] "ncor"

[[38]]
[1] "lant"

[[39]]
[1] "buqu"

[[40]]
[1] "bany"

[[41]]
[1] "ffal"

[[42]]
[1] "w Yo"

[[43]]
[1] "arlo"

[[44]]
[1] "leig"

[[45]]
[1] "smar"

[[46]]
[1] "ncin"

[[47]]
[1] "evel"

[[48]]
[1] "lumb"

[[49]]
[1] "laho"

[[50]]
[1] "rtla"

[[51]]
[1] "ilad"

[[52]]
[1] "ttsb"

[[53]]
[1] "ovid"

[[54]]
[1] "lumb"

[[55]]
[1] "oux "

[[56]]
[1] "mphi"

[[57]]
[1] "shvi"

[[58]]
[1] "llas"

[[59]]
[1] " Pas"

[[60]]
[1] "usto"

[[61]]
[1] "lt L"

[[62]]
[1] "rlin"

[[63]]
[1] "rfol"

[[64]]
[1] "chmo"

[[65]]
[1] "attl"

[[66]]
[1] "okan"

[[67]]
[1] "arle"

[[68]]
[1] "lwau"

[[69]]
[1] "eyen"

[[70]]
[1] "n Ju"

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

[[1]]
[1] 6

[[2]]
[1] 68

[[3]]
[1] 78

[[4]]
[1] 171

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

    setosa versicolor  virginica 
     1.462      4.260      5.552 
       5        6        7        8        9 
23.61538 29.44444 59.11538 59.96154 31.44828 
  L   M   H 
655 475 390 


Group.1    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

Group.1 mpg      cyl disp     hp        drat     wt       qsec     vs       
1 4       26.66364 4   105.1364  82.63636 4.070909 2.285727 19.13727 0.9090909
2 6       19.74286 6   183.3143 122.28571 3.585714 3.117143 17.97714 0.5714286
3 8       15.10000 8   353.1000 209.21429 3.229286 3.999214 16.77214 0.0000000
  am        gear     carb    
1 0.7272727 4.090909 1.545455
2 0.4285714 3.857143 3.428571
3 0.1428571 3.285714 3.500000

feed      weight  
1 casein    323.5833
2 horsebean 160.2000
3 linseed   218.7500
4 meatmeal  276.9091
5 soybean   246.4286
6 sunflower 328.9167

wool tension breaks  
1 A    L       44.55556
2 B    L       28.22222
3 A    M       24.00000
4 B    M       28.77778
5 A    H       24.55556
6 B    H       18.77778

Month Ozone    Temp    
1 5     23.61538 66.73077
2 6     29.44444 78.22222
3 7     59.11538 83.88462
4 8     59.96154 83.96154
5 9     31.44828 76.89655

alcgp     tobgp    ncases ncontrols
1  0-39g/day 0-9g/day  9     261      
2  40-79     0-9g/day 34     179      
3  80-119    0-9g/day 19      61      
4  120+      0-9g/day 16      24      
5  0-39g/day 10-19    10      84      
6  40-79     10-19    17      85      
7  80-119    10-19    19      49      
8  120+      10-19    12      18      
9  0-39g/day 20-29     5      42      
10 40-79     20-29    15      62      
11 80-119    20-29     6      16      
12 120+      20-29     7      12      
13 0-39g/day 30+       5      28      
14 40-79     30+       9      29      
15 80-119    30+       7      12      
16 120+      30+      10      13

Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

supp dose len  
1 OJ   0.5  13.23
2 VC   0.5   7.98
3 OJ   1.0  22.70
4 VC   1.0  16.77
5 OJ   2.0  26.06
6 VC   2.0  26.14

In [2]:
############### user defined functions ##################
myFun <- function(x,y) {
      x+y
      letters[1:5] # last statement will be printed to the console
}

sum_of_squares <- function(x,y) {
  x^2 + y^2
}
###########
pow <- function(x, y) {
  # function to print x raised to the power y
  result <- x^y
  print(paste(x,"raised to the power", y, "is", result))
}
######## default argument
new.function <- function(a = 3, b = 6) { #while creating fun only assigning values
  result <- a * b
  print(result)
}

 new.function() #default values will be operate
#[1] 18
 new.function(2,3) # replaced default values with this new values
#[1] 6
 new.function(2) # replaced only first argument
#[1] 12
 new.function(b=2) # replaced only b 
#[1] 6
 new.function(b=2,a=3) # even order is not care when we assign values
# [1] 6
 ###################################
#  MyThirdFun <- function(n, y = 2) 
#  {
#    # Compute the power of n to the y
#    n^y  
#  }
#  MyThirdFun(2,3) 
#  MyThirdFun(2)
#  MyThirdFun() # Error: when the arguments are not default we must pass some values-
 
 ###########
 add <- function(x,y=1,z=2){
   x+y
   x+z 
 }
 
 add(5)
 ####################
 add <- function(x,y=1,z=2){
   print(x+y)
   x+z 
 }
 
 add(5)
 ##########################
 add <- function(x,y=1,z=2){
   return(x+y)
   x+z 
 }
 
 add(5)
############## 
 add <- function(x,y=1,z=2){
   return(x+y)
   print(x+z) # print ignored because of return before that
 }
 
 add(5)
 ###################
 
 add <- function(x,y=1,z=2){
   print(x+z)
   return(x+y) # return should be your last statment when you want to use prints 
 }
 
 add(5)
#####################
 fahr_to_kelvin <- function(temp) {
   kelvin <- ((temp - 32) * (5 / 9)) + 273.15
   return(kelvin)
 }
fahr_to_kelvin(25)
### functions in r called as first class objects
# treat every function is just like other objects
# we can pass them into other functions like other objects(vectors, lists,...etc)
sum(2,prod(3,which(letters=="h")))

############# lazy evaluation
fun <- function(a,b){
  a^2
}
fun(2,x/0) # value of b is not using here in the function

#####
fun <- function(x){
  10  # not using the x value with in the logic
}
fun("sumendar")

#############
fun <- function(x){
  nchar(x)+10  #using the x value with in the logic
} 
fun("sumendar")
########################
##nameless or ananymous functions
(function(x) x*10)(5)
(function(x,y) x*y)(5,6)
#########
args(add) # args function will print the arguments list
args(sample)
dates <- 1:30
sample(dates, 16) # sample "size = 16"
sample(16, dates) # undesired results; wanted "size = 16"
sample(size = 16, x = dates) # gives desired result

sample(s = 16, x = dates) # sampling w/ replacement
sample(s = 16, x = dates, r = TRUE) # sampling w/ replacement
sample(s = 16, x = dates, rep = TRUE) # sampling w/ replacement
sample(s = 16, x = dates, replace = TRUE) # sampling w/ replacement

################ apply family of functions ####################

#############apply
apply(mtcars, 2, mean) # columnwise
apply(mtcars, 2, median)
apply(mtcars, 2, max)
apply(mtcars, 1, max) #rowwise
apply(mtcars, 1, min)
apply(mtcars, 1, mean)

############# lapply
lapply(list(2:10), sum)
lapply(list(2:10,5:7), sum)
lapply(month.name, nchar)
lapply(names(precip), toupper)

[1] 18
[1] 6
[1] 12
[1] 6
[1] 6


[1] 7

[1] 6


[1] 7

[1] 6

[1] 6

[1] 7


[1] 6

[1] 269.2611

[1] 26

[1] 4

[1] 10

[1] 18

[1] 50

[1] 30

function (x, y = 1, z = 2) 
NULL

function (x, size, replace = FALSE, prob = NULL) 
NULL

[1] 13 21 10  1 24 18  5 20 28  2 16 25 23 15  9 14

[1] 16

[1] 11 27  9 20 28 12 29 19  8 30  5 16 15  2 18  4

[1]  3  5 21 12 18 15  2  9  8 25 28 26 22 11 14 30

[1] 26 23 23 24 15 30  8  6 22 24 10  8 12 17 10  9

[1] 16 27  8  7 27 17  5  8 25 26  5 13 15 23 27 25

[1] 24 16 29 25 24  6  1  4  7 23  1 12  5 12 23 28

mpg        cyl       disp         hp       drat         wt       qsec 
 20.090625   6.187500 230.721875 146.687500   3.596563   3.217250  17.848750 
        vs         am       gear       carb 
  0.437500   0.406250   3.687500   2.812500

mpg     cyl    disp      hp    drat      wt    qsec      vs      am    gear 
 19.200   6.000 196.300 123.000   3.695   3.325  17.710   0.000   0.000   4.000 
   carb 
  2.000

mpg     cyl    disp      hp    drat      wt    qsec      vs      am    gear 
 33.900   8.000 472.000 335.000   4.930   5.424  22.900   1.000   1.000   5.000 
   carb 
  8.000

Mazda RX4       Mazda RX4 Wag          Datsun 710      Hornet 4 Drive 
              160.0               160.0               108.0               258.0 
  Hornet Sportabout             Valiant          Duster 360           Merc 240D 
              360.0               225.0               360.0               146.7 
           Merc 230            Merc 280           Merc 280C          Merc 450SE 
              140.8               167.6               167.6               275.8 
         Merc 450SL         Merc 450SLC  Cadillac Fleetwood Lincoln Continental 
              275.8               275.8               472.0               460.0 
  Chrysler Imperial            Fiat 128         Honda Civic      Toyota Corolla 
              440.0                78.7                75.7                71.1 
      Toyota Corona    Dodge Challenger         AMC Javelin          Camaro Z28 
              120.1               318.0               304.0               350.0 
   Pontiac Firebird           Fiat X1-9       Porsche 914-2        Lotus Europa 
              400.0                79.0               120.3               113.0 
     Ford Pantera L        Ferrari Dino       Maserati Bora          Volvo 142E 
              351.0               175.0               335.0               121.0

Mazda RX4       Mazda RX4 Wag          Datsun 710      Hornet 4 Drive 
                  0                   0                   1                   0 
  Hornet Sportabout             Valiant          Duster 360           Merc 240D 
                  0                   0                   0                   0 
           Merc 230            Merc 280           Merc 280C          Merc 450SE 
                  0                   0                   0                   0 
         Merc 450SL         Merc 450SLC  Cadillac Fleetwood Lincoln Continental 
                  0                   0                   0                   0 
  Chrysler Imperial            Fiat 128         Honda Civic      Toyota Corolla 
                  0                   1                   1                   1 
      Toyota Corona    Dodge Challenger         AMC Javelin          Camaro Z28 
                  0                   0                   0                   0 
   Pontiac Firebird           Fiat X1-9       Porsche 914-2        Lotus Europa 
                  0                   1                   0                   1 
     Ford Pantera L        Ferrari Dino       Maserati Bora          Volvo 142E 
                  0                   0                   0                   1

Mazda RX4       Mazda RX4 Wag          Datsun 710      Hornet 4 Drive 
           29.90727            29.98136            23.59818            38.73955 
  Hornet Sportabout             Valiant          Duster 360           Merc 240D 
           53.66455            35.04909            59.72000            24.63455 
           Merc 230            Merc 280           Merc 280C          Merc 450SE 
           27.23364            31.86000            31.78727            46.43091 
         Merc 450SL         Merc 450SLC  Cadillac Fleetwood Lincoln Continental 
           46.50000            46.35000            66.23273            66.05855 
  Chrysler Imperial            Fiat 128         Honda Civic      Toyota Corolla 
           65.97227            19.44091            17.74227            18.81409 
      Toyota Corona    Dodge Challenger         AMC Javelin          Camaro Z28 
           24.88864            47.24091            46.00773            58.75273 
   Pontiac Firebird           Fiat X1-9       Porsche 914-2        Lotus Europa 
           57.37955            18.92864            24.77909            24.88027 
     Ford Pantera L        Ferrari Dino       Maserati Bora          Volvo 142E 
           60.97182            34.50818            63.15545            26.26273

[[1]]
[1] 54

[[1]]
[1] 54

[[2]]
[1] 18

[[1]]
[1] 7

[[2]]
[1] 8

[[3]]
[1] 5

[[4]]
[1] 5

[[5]]
[1] 3

[[6]]
[1] 4

[[7]]
[1] 4

[[8]]
[1] 6

[[9]]
[1] 9

[[10]]
[1] 7

[[11]]
[1] 8

[[12]]
[1] 8

[[1]]
[1] "MOBILE"

[[2]]
[1] "JUNEAU"

[[3]]
[1] "PHOENIX"

[[4]]
[1] "LITTLE ROCK"

[[5]]
[1] "LOS ANGELES"

[[6]]
[1] "SACRAMENTO"

[[7]]
[1] "SAN FRANCISCO"

[[8]]
[1] "DENVER"

[[9]]
[1] "HARTFORD"

[[10]]
[1] "WILMINGTON"

[[11]]
[1] "WASHINGTON"

[[12]]
[1] "JACKSONVILLE"

[[13]]
[1] "MIAMI"

[[14]]
[1] "ATLANTA"

[[15]]
[1] "HONOLULU"

[[16]]
[1] "BOISE"

[[17]]
[1] "CHICAGO"

[[18]]
[1] "PEORIA"

[[19]]
[1] "INDIANAPOLIS"

[[20]]
[1] "DES MOINES"

[[21]]
[1] "WICHITA"

[[22]]
[1] "LOUISVILLE"

[[23]]
[1] "NEW ORLEANS"

[[24]]
[1] "PORTLAND"

[[25]]
[1] "BALTIMORE"

[[26]]
[1] "BOSTON"

[[27]]
[1] "DETROIT"

[[28]]
[1] "SAULT STE. MARIE"

[[29]]
[1] "DULUTH"

[[30]]
[1] "MINNEAPOLIS/ST PAUL"

[[31]]
[1] "JACKSON"

[[32]]
[1] "KANSAS CITY"

[[33]]
[1] "ST LOUIS"

[[34]]
[1] "GREAT FALLS"

[[35]]
[1] "OMAHA"

[[36]]
[1] "RENO"

[[37]]
[1] "CONCORD"

[[38]]
[1] "ATLANTIC CITY"

[[39]]
[1] "ALBUQUERQUE"

[[40]]
[1] "ALBANY"

[[41]]
[1] "BUFFALO"

[[42]]
[1] "NEW YORK"

[[43]]
[1] "CHARLOTTE"

[[44]]
[1] "RALEIGH"

[[45]]
[1] "BISMARK"

[[46]]
[1] "CINCINNATI"

[[47]]
[1] "CLEVELAND"

[[48]]
[1] "COLUMBUS"

[[49]]
[1] "OKLAHOMA CITY"

[[50]]
[1] "PORTLAND"

[[51]]
[1] "PHILADELPHIA"

[[52]]
[1] "PITTSBURG"

[[53]]
[1] "PROVIDENCE"

[[54]]
[1] "COLUMBIA"

[[55]]
[1] "SIOUX FALLS"

[[56]]
[1] "MEMPHIS"

[[57]]
[1] "NASHVILLE"

[[58]]
[1] "DALLAS"

[[59]]
[1] "EL PASO"

[[60]]
[1] "HOUSTON"

[[61]]
[1] "SALT LAKE CITY"

[[62]]
[1] "BURLINGTON"

[[63]]
[1] "NORFOLK"

[[64]]
[1] "RICHMOND"

[[65]]
[1] "SEATTLE TACOMA"

[[66]]
[1] "SPOKANE"

[[67]]
[1] "CHARLESTON"

[[68]]
[1] "MILWAUKEE"

[[69]]
[1] "CHEYENNE"

[[70]]
[1] "SAN JUAN"

In [3]:
################ apply function on matrices

mnthMat <- matrix(month.name,3,4)
mnthMat
apply(mnthMat, 2, nchar) # column wise 
apply(mnthMat, 1, nchar) # row wise 

####################################### apply function on arrays
mnthArr <- array(seq(1,18),dim = c(2,3,3))
mnthArr

#rowwise operation
apply(mnthArr, 1, mean) 
# is nothing but
mean(c(1,3,5,7,9,11,13,15,17))
# or 
mean(c(mnthArr[,,1][1,],mnthArr[,,2][1,],mnthArr[,,3][1,]))

#column wise operation
apply(mnthArr, 2, mean) 
# is nothing but
mean(c(1,2,7,8,13,14))
# or 
mean(c(mnthArr[,,1][,1],mnthArr[,,2][,1],mnthArr[,,3][,1]))

#table wise operation
apply(mnthArr, 3, mean)
# is nothing but
mean(1:6)
# or 
mean(mnthArr[,,1])

############################################
############### 
lapply(month.name, nchar)
sapply(month.name, nchar)
#############
str(iris)
print(tapply(iris$Sepal.Length, iris$Species, mean))
print(tapply(mtcars$mpg, mtcars$cyl, mean))
print(tapply(mtcars$mpg, mtcars$carb, mean))
print(tapply(mtcars$mpg, mtcars$gear, mean))

aggregate(iris[-5], list(iris$Species), mean)
aggregate(iris[1:4], list(iris$Species), mean)
aggregate(iris[,1:4], list(iris$Species), mean)

## Formulas, one ~ one, one ~ many, many ~ one, and many ~ many:
aggregate(weight ~ feed, data = chickwts, mean)
# is same as 
print(tapply(airquality$Wind , airquality$Month, mean))
# is same as 
print(with(airquality, tapply(Wind , Month, mean)))

aggregate(breaks ~ wool + tension, data = warpbreaks, mean)
# is same as
aggregate(warpbreaks$breaks,list(warpbreaks$wool,warpbreaks$tension), mean)

aggregate(cbind(Ozone, Temp) ~ Month, data = airquality, mean)
aggregate(cbind(ncases, ncontrols) ~ alcgp + tobgp, data = esoph, sum)

## Dot notation:
aggregate(. ~ Species, data = iris, mean)
aggregate(len ~ ., data = ToothGrowth, mean)

###### mapply
l1 <- list(a = c(1:10), b = c(11:20))
l2 <- list(c = c(21:30), d = c(31:40))
l1
l2
print(mapply(sum, l1$a, l1$b, l2$c, l2$d))
sum(c(1,11,21,31))
print(mapply(sum, l1))
sum(1:10)
sum(11:20)
print(mapply(sum, l1,l2))

########## by function

b <- by(iris[, 1:4], iris$Species, colMeans)
b

####################### with()

mtcars$mpg[mtcars$cyl == 8  &  mtcars$disp > 350]
with(mtcars, mpg[cyl == 8  &  disp > 350]) # we can avoid using $ notation by with() function

############## attach()

x <- data.frame(Subtype= c("A","A","B","A","B","B","A","B","A","B"), 
                Gender= rep(c("m","f"),each=5), 
                Expression = c(-0.54,-0.8,-1.03,-0.41,-1.31,-0.66,-0.43,1.01,-1.15,0.14))

x
x$Expression
# Expression  # you will get an error
attach(x) #using attach
Expression  # you will get answer
detach(x)
# Expression  # error
x$Expression

[,1]     [,2]  [,3]      [,4]    
[1,] January  April July      October 
[2,] February May   August    November
[3,] March    June  September December

[,1] [,2] [,3] [,4]
[1,] 7    5    4    7   
[2,] 8    3    6    8   
[3,] 5    4    9    8

[,1] [,2] [,3]
[1,] 7    8    5   
[2,] 5    3    4   
[3,] 4    6    9   
[4,] 7    8    8

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

[1]  9 10

[1] 9

[1] 9

[1]  7.5  9.5 11.5

[1] 7.5

[1] 7.5

[1]  3.5  9.5 15.5

[1] 3.5

[1] 3.5

[[1]]
[1] 7

[[2]]
[1] 8

[[3]]
[1] 5

[[4]]
[1] 5

[[5]]
[1] 3

[[6]]
[1] 4

[[7]]
[1] 4

[[8]]
[1] 6

[[9]]
[1] 9

[[10]]
[1] 7

[[11]]
[1] 8

[[12]]
[1] 8

January  February     March     April       May      June      July    August 
        7         8         5         5         3         4         4         6 
September   October  November  December 
        9         7         8         8

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
    setosa versicolor  virginica 
     5.006      5.936      6.588 
       4        6        8 
26.66364 19.74286 15.10000 
       1        2        3        4        6        8 
25.34286 22.40000 16.30000 15.79000 19.70000 15.00000 
       3        4        5 
16.10667 24.53333 21.38000 


Group.1    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

Group.1    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

Group.1    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

feed      weight  
1 casein    323.5833
2 horsebean 160.2000
3 linseed   218.7500
4 meatmeal  276.9091
5 soybean   246.4286
6 sunflower 328.9167

        5         6         7         8         9 
11.622581 10.266667  8.941935  8.793548 10.180000 
        5         6         7         8         9 
11.622581 10.266667  8.941935  8.793548 10.180000 


wool tension breaks  
1 A    L       44.55556
2 B    L       28.22222
3 A    M       24.00000
4 B    M       28.77778
5 A    H       24.55556
6 B    H       18.77778

Month Ozone    Temp    
1 5     23.61538 66.73077
2 6     29.44444 78.22222
3 7     59.11538 83.88462
4 8     59.96154 83.96154
5 9     31.44828 76.89655

alcgp     tobgp    ncases ncontrols
1  0-39g/day 0-9g/day  9     261      
2  40-79     0-9g/day 34     179      
3  80-119    0-9g/day 19      61      
4  120+      0-9g/day 16      24      
5  0-39g/day 10-19    10      84      
6  40-79     10-19    17      85      
7  80-119    10-19    19      49      
8  120+      10-19    12      18      
9  0-39g/day 20-29     5      42      
10 40-79     20-29    15      62      
11 80-119    20-29     6      16      
12 120+      20-29     7      12      
13 0-39g/day 30+       5      28      
14 40-79     30+       9      29      
15 80-119    30+       7      12      
16 120+      30+      10      13

Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

supp dose len  
1 OJ   0.5  13.23
2 VC   0.5   7.98
3 OJ   1.0  22.70
4 VC   1.0  16.77
5 OJ   2.0  26.06
6 VC   2.0  26.14

$a
 [1]  1  2  3  4  5  6  7  8  9 10

$b
 [1] 11 12 13 14 15 16 17 18 19 20

$c
 [1] 21 22 23 24 25 26 27 28 29 30

$d
 [1] 31 32 33 34 35 36 37 38 39 40

 [1]  64  68  72  76  80  84  88  92  96 100


[1] 64

  a   b 
 55 155 


[1] 55

[1] 155

  a   b 
310 510 


iris$Species: setosa
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       5.006        3.428        1.462        0.246 
------------------------------------------------------------ 
iris$Species: versicolor
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       5.936        2.770        4.260        1.326 
------------------------------------------------------------ 
iris$Species: virginica
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       6.588        2.974        5.552        2.026 

[1] 18.7 14.3 10.4 10.4 14.7 19.2 15.8

[1] 18.7 14.3 10.4 10.4 14.7 19.2 15.8

Subtype Gender Expression
1  A       m      -0.54     
2  A       m      -0.80     
3  B       m      -1.03     
4  A       m      -0.41     
5  B       m      -1.31     
6  B       f      -0.66     
7  A       f      -0.43     
8  B       f       1.01     
9  A       f      -1.15     
10 B       f       0.14

[1] -0.54 -0.80 -1.03 -0.41 -1.31 -0.66 -0.43  1.01 -1.15  0.14

[1] -0.54 -0.80 -1.03 -0.41 -1.31 -0.66 -0.43  1.01 -1.15  0.14

[1] -0.54 -0.80 -1.03 -0.41 -1.31 -0.66 -0.43  1.01 -1.15  0.14

In [2]:
# setwd("C:/Users/user/Downloads/DSwRandP-apr18-master/DSwRandP-apr18-master/FunctionsAndApplyFamily")
sum(1,2) # inbuilt function to add elements
# sum1(1,2) # 
# to create a function
sum1 <- function(x,y) {
  x+y
}
sum <- c(1,2)
class(sum)
letters <- c(1,2)
letters

rm(letters)
obj <- letters
obj
letters
sum(1,2)
sum1(1,2)

abs(-3)
abs(-1.3)
sqrt(64)	# square root function
8^2 # exponential
round(3.455) # nearest integer value
round(3.955)
ceiling(3.475)	
floor(3.475)	

ceiling(3.175)#lookin at top	
round(3.175)	
floor(3.475)	#looking at bottom
floor(3.9999999)	#looking at bottom
round(3.9999999)
trunc(5.99)
log(1)
log2(16)
log(2.71828)
# e =2.71828
toupper("sumendar")
tolower("SUMENDAR")

[1] 3

[1] "numeric"

[1] 1 2

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] 3

[1] 3

[1] 3

[1] 1.3

[1] 8

[1] 64

[1] 3

[1] 4

[1] 4

[1] 3

[1] 4

[1] 3

[1] 3

[1] 3

[1] 4

[1] 5

[1] 0

[1] 4

[1] 0.9999993

[1] "SUMENDAR"

[1] "sumendar"

In [9]:
#functions

sum1(2,3)


sum1(56,78)
# without arguments
display <- function()
{
  print("lucid it solutions")
}
display()

# function define
sum_of_squares <- function(x,y) {  
  x^2 + y^2
}
sum_of_squares(3,4) # function call
#example
# function to print x raised to the power y

pow <- function(x, y) {
  result <- x^y
  print(paste(x,"raised to the power", y, "is", result))
}
pow(2,3)
#Default Arguments
# Create a function with arguments.
new.function <- function(a = 3, b = 6) {
  result <- a * b
  #print(result)
  return(result) # to print to the console
}


new.function <- function(a=5, b) {
  result <- a * b
  #print(result)
  return(result) # to print to the console
}
#new.function(,3)  #this will take the value 3 for b  


#new.function() # this will print default values result
new.function(2,3) # 
#new.function(2)
#new.function(,2)


add <- function(x,y=1,z=2){
  x+y
  x+z

}
add(5)

add <- function(x,y=1,z=2){
  x+y
  x+z
  return(c(x+y,x+z))  
}
add(5)



add <- function(x,y=1,z=2){
  x+y
  x+z
  return(paste(x+y,x+z))  
}
add(5)


add <- function(x,y=1,z=2){
  x+y
  x+z
  print(paste(x+y,x+z))  
}
add(5)

fahr_to_kelvin <- function(temp) {
  kelvin <- ((temp - 32) * (5 / 9)) + 273.15
  return(kelvin)
}

fahr_to_kelvin(35)
# Named Arguments¶

pow(8, 2)
pow(x = 8, y = 2)
pow(y = 2, x = 8)
pow(2, x = 8)
pow(2, y = 8)
class(substring(pow(sum(1,2),5), 3,8)) # functions with in another function
# Lazy evaluation

fun <- function(a,b){
  a^2
}

fun(2,x/0)

fun <- function(a,b){
  b^2
}

fun(2,x/0)

fun <- function(a,b){
  b^2
}

fun(2,3/0)
x <- 5
fun(2,x/1)
# Lazy evaluation of args

fun <- function(x){
  10
}
fun("hello")
#functions without name
(function(x) x*10)(5)


x <- 5 # global assignment of x is not used by the fun
fun <- function(x){
  #parameter x is passed by value (copy)
  x <- x+1 # local variable is modified
  print(x)
}
fun(1) # prints 
#fun() # prints 


input_1 = 20
mySum <- function(input_1, input_2 = 10) {
  output <- input_1 + input_2
  return(output)
}
mySum(input_1 = 1, 3)
mySum(input_1 = 1, 3)



input_1 = 20
mySum <- function(input_1a=input_1, input_2 = 10) {
  output <- input_1a + input_2
  return(output)
}

mySum()

[1] 5

[1] 134

[1] "lucid it solutions"


[1] 25

[1] "2 raised to the power 3 is 8"


[1] 6

[1] 7

[1] 6 7

[1] "6 7"

[1] "6 7"


[1] 274.8167

[1] "8 raised to the power 2 is 64"
[1] "8 raised to the power 2 is 64"
[1] "8 raised to the power 2 is 64"
[1] "8 raised to the power 2 is 64"
[1] "2 raised to the power 8 is 256"
[1] "3 raised to the power 5 is 243"


[1] "character"

[1] 4

[1] Inf

[1] Inf

[1] 25

[1] 10

[1] 50

[1] 2


[1] 4

[1] 4

[1] 30

In [1]:
sum(3,4)
prod(3,4)
sum(3,4) + prod(3,4)
sum(8,4) + prod(8,4)
sum(9,4) + prod(9,4)
sum(5,3) + prod(5,3)

sumprod <- function(x,y){ # 
  sum(x,y) + prod(x,y)
}

sumprod(8,4) #invoking

x <- seq(2,14)
y <- x+1
sumprod(x,y) #invoking the function using x and y vectors
options(scipen = 999) # to print exponential values as normal values
sumprod(x,y)

tu<- toupper("lucid it solutions") # to become uppercase
tolower(tu)  # to print as lower case
substring("lucid it solutions", 3,5)
substring("lucid it solutions", 5,8)


sumprod <- function(x,y){ # 
  sum(x,y)
  sum(x,y) + prod(x,y) #last statement result only invoked
}

sumprod(8,4) #invoking
sum(8,4)



sumprod <- function(x,y){ # 
  return(sum(x,y)) # this statement will execute last
  sum(x,y) + prod(x,y) 
}
sumprod(8,4) #invoking

sumprod <- function(x,y){ # 
  return(sum(x,y)) # this statement will execute last
  return(sum(x,y) + prod(x,y)) 
}
sumprod(8,4) #invoking


sumprod <- function(x,y){ # 
  return(c(sum(x,y), (sum(x,y) + prod(x,y)), "hello")) # return argument should only one
}
sumprod(8,4) #invoking

########## default arguments

new.function <- function(a = 3, b = 6) {  # givilng arguement values as default
  result <- a * b
  print(result)
}
new.function() # invoking without arguements
new.function(5) # invoking with single arguement
new.function(b=5) # invoking using name
new.function(5,3) # normal 
new.function(b=4,a=2) #naming 


add <- function(x,y=1,z=2){
  x+y
  x+z
}
add(5) # last statement wiill evaluated

fahr_to_kelvin <- function(temp) {
  kelvin <- ((temp - 32) * (5 / 9)) + 273.15
  return(kelvin)
}

# functions Can be passed as arguments to other functions
substring(class(prod(sum(2,3),4)), 3,6)



### lazy evaluation
fun <- function(a,b){
  a^2
}

fun(2,x/0)
fun(2,";")

fun <- function(x){
  10
}

fun("hello")

fun <- function(x){
  paste(x,10)
}

fun("hello")

(function(x) x*10)(5)  #nameless function
  

x <- 5 # global assignment of x is not used by the fun
fun <- function(x){
  #parameter x is passed by value (copy)
  x <- x+1 # local variable is modified
  print(x)
}
fun(1) # prints 
# fun() # error


x1 <- 5 # global assignment of x is not used by the fun
fun <- function(x=x1){
  #parameter x is passed by value (copy)
  x <- x+1 # local variable is modified
  print(x)
}
fun() # result 6

[1] 7

[1] 12

[1] 19

[1] 44

[1] 49

[1] 23

[1] 44

[1] 5.700041e+22

[1] 57000408424139982897152

[1] "lucid it solutions"

[1] "cid"

[1] "d it"

[1] 44

[1] 12

[1] 12

[1] 12

[1] "12"    "44"    "hello"

[1] 18
[1] 30
[1] 15
[1] 15
[1] 8


[1] 7

[1] "meri"

[1] 4

[1] 4

[1] 10

[1] "hello 10"

[1] 50

[1] 2
[1] 6
