<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-structures" data-toc-modified-id="Data-structures-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data structures</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Atomic-vectors" data-toc-modified-id="Atomic-vectors-1.0.1"><span class="toc-item-num">1.0.1&nbsp;&nbsp;</span>Atomic vectors</a></span></li><li><span><a href="#Lists-(recursive-vectors)" data-toc-modified-id="Lists-(recursive-vectors)-1.0.2"><span class="toc-item-num">1.0.2&nbsp;&nbsp;</span>Lists (recursive vectors)</a></span></li><li><span><a href="#matrix-and-arrays" data-toc-modified-id="matrix-and-arrays-1.0.3"><span class="toc-item-num">1.0.3&nbsp;&nbsp;</span>matrix and arrays</a></span><ul class="toc-item"><li><span><a href="#using-cbind-and-rbind" data-toc-modified-id="using-cbind-and-rbind-1.0.3.1"><span class="toc-item-num">1.0.3.1&nbsp;&nbsp;</span>using cbind and rbind</a></span></li><li><span><a href="#Vector-and-Matrix-Operations" data-toc-modified-id="Vector-and-Matrix-Operations-1.0.3.2"><span class="toc-item-num">1.0.3.2&nbsp;&nbsp;</span>Vector and Matrix Operations</a></span></li></ul></li><li><span><a href="#data-frame" data-toc-modified-id="data-frame-1.0.4"><span class="toc-item-num">1.0.4&nbsp;&nbsp;</span>data frame</a></span><ul class="toc-item"><li><span><a href="#using-cbind-and-rbind" data-toc-modified-id="using-cbind-and-rbind-1.0.4.1"><span class="toc-item-num">1.0.4.1&nbsp;&nbsp;</span>using cbind and rbind</a></span></li><li><span><a href="#using-expand.grid()" data-toc-modified-id="using-expand.grid()-1.0.4.2"><span class="toc-item-num">1.0.4.2&nbsp;&nbsp;</span>using expand.grid()</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Data-Types,-Class-and-Attributes" data-toc-modified-id="Data-Types,-Class-and-Attributes-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Data Types, Class and Attributes</a></span></li><li><span><a href="#Special-values" data-toc-modified-id="Special-values-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Special values</a></span><ul class="toc-item"><li><span><a href="#NA" data-toc-modified-id="NA-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>NA</a></span></li><li><span><a href="#NULL" data-toc-modified-id="NULL-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>NULL</a></span></li><li><span><a href="#Inf" data-toc-modified-id="Inf-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Inf</a></span></li><li><span><a href="#NaN" data-toc-modified-id="NaN-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>NaN</a></span></li></ul></li><li><span><a href="#Coercion" data-toc-modified-id="Coercion-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Coercion</a></span><ul class="toc-item"><li><span><a href="#Internal-(implicit)-coercion" data-toc-modified-id="Internal-(implicit)-coercion-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Internal (implicit) coercion</a></span></li><li><span><a href="#External-coercion-and-testing-objects" data-toc-modified-id="External-coercion-and-testing-objects-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>External coercion and testing objects</a></span></li></ul></li><li><span><a href="#Reshaping-R-Objects" data-toc-modified-id="Reshaping-R-Objects-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Reshaping R Objects</a></span><ul class="toc-item"><li><span><a href="#for-vectors-and-matrices" data-toc-modified-id="for-vectors-and-matrices-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>for vectors and matrices</a></span></li><li><span><a href="#for-dataframes" data-toc-modified-id="for-dataframes-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>for dataframes</a></span></li></ul></li><li><span><a href="#siwrl-Package:" data-toc-modified-id="siwrl-Package:-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>siwrl Package:</a></span></li></ul></div>

![Imgur](https://i.imgur.com/VXYtqs9.jpg)

** Objects **
> Objects are simply a definition for a type of data to be stored  
e.g., vector, matrix, array, data frame, list, function

## Data structures
A perticular way of organizing data 


	* Atomic vectors (basic data types in R and is pretty much the workhorse of R)
	* Recursive lists (List is a special vector. Each element can be a different class)

#### Atomic vectors

* A vector can be a vector of characters, logical, integers or numeric.  
You can create vectors by concatenating them using the `c()` function.  
Various examples:  
`x <- c(1, 2, 3)`  
x is a numeric vector. These are the most common kind. They are numeric objects and are treated as double precision real numbers. To explicitly create integers, add a L at the end.   
`x1 <- c(1L, 2L, 3L)` 
You can also have logical vectors.  
`y <- c(TRUE, TRUE, FALSE, FALSE)`  
Finally you can have character vectors:  
`z <- c("Alec", "Dan", "Rob", "Rich")`  

```{r}
#The general pattern is vector(class of object, length). 
Create an empty vector with vector()
x <- vector() # will get default logical(0) values
# with a specified type and pre-defined length
x <- vector(length = 10) # will get default 10 FALSE values 
# with a length and type
vector(mode = "character", length = 10) # is equalent to character(10)
vector("numeric", length = 5)  # is equalent to numeric(5)
vector("integer", 10)
vector(mode = "logical", 8)
vector("complex", 5)
```

**Vectors may only have one type**   
* atomic vectors are homogeneous. This means that every element within a single atomic vector has to be of the same type
* R will create a resulting vector that is the least common denominator. The coercion will move towards the one that's easiest to coerce to.

**Some Function for Vectors**

| Functions      | Description                                                                                             |
|----------------|---------------------------------------------------------------------------------------------------------|
| `c()`          | combines values, vectors, and/or lists to create new objects                                            |
| `unique()`     | returns a vector containing one element for each unique value in the vector                             |
| `duplicated()` | returns a logical vector which tells if elements of a vector are duplicated with regard to previous one |
| `rev()`        | reverse the order of element in a vector                                                                |
| `sort()`       | sorts the elements in a vector                                                                          |
| `append()`     | append or insert elements in a vector.                                                                                                     |
| `sum()`        | sum of the elements of a vector                                                                                                      |
| `min()`        | minimum value in a vector                                                                                                     |
| `max()`        | maximum value in a vector                                                                                                      |
| `cumsum`   | cumulative sum       | 
| `diff`    | x[i+1] - x[i]        | 
| `prod`     | product              | 
| `cumprod`  | cumulative product   | 
| `mean`     | average                 | 
| `median`   | median               | 
| `range`    | range (minimum and maximum)               | 
| `order`    | order                | 
| `rank`     | rank                 | 
| `sample`   | random sample        | 
| `quartile` | percentile           | 
| `var`      | variance, covariance | 
| `sd`       | standard deviation   | 


**Other Functions**  
```{r}
(x <- c(sort(sample(1:20, 9)), NA))
(y <- c(sort(sample(3:23, 7)), NA))
union(x, y)
intersect(x, y)
setdiff(x, y)
setdiff(y, x)
setequal(x, y)
which.min(x)
which.max(x)
match(x,y)
```  

#### Lists (recursive vectors)

* List is a special vector. Each element can be a different class.
* lists act as containers
* Unlike atomic vectors, its contents are not restricted to a single type
* a list can be anything, and two elements within a list can be of different types!
* Lists are sometimes called recursive vectors, because a list can contain other lists

** Create a ists using list function**      
`x <- list(1, "a", TRUE, 1+4i)`    

R also has many data structures. These include
	* matrix and arrays
    * data frame	

![Imgur](https://i.imgur.com/c73sZAd.png?1)

#### matrix and arrays

* Stacking multiple matrices
* Matrices in R can be thought of as vectors indexed using two indices instead of one

In [1]:
m <- matrix(c(47,48,52,36,89,45,1,2,-25), nrow = 3, ncol = 3)
m
# this code creates a 3 by 3 matrix

[,1] [,2] [,3]
[1,] 47   36     1 
[2,] 48   89     2 
[3,] 52   45   -25

##### using cbind and rbind
(to create a matrix)

In [8]:
# 3 column matrix with column dimnames
m <- cbind(Index = c(1:3), Age = c(30, 45, 34), Salary = c(500, 600, 550)) 
class(m)
m

[1] "matrix"

Index Age Salary
[1,] 1     30  500   
[2,] 2     45  600   
[3,] 3     34  550

* If a higher dimension vector is desired, then use the array() function to generate the n-dimensional object. A 3x3x3 array can be created as follows:

In [7]:
a <- array(1:27, dim=c(3,3,3))
print(a)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27



**To check the `dimensions` of array or matrix**    
`dim()`  will give you the number of rows, columns and slices   
`length(dim())`  will give actual dimension as a single number  

In [9]:
# for matrix
dim(m)
length(dim(m))
# for array
dim(a)
length(dim(a))


[1] 3 3

[1] 2

[1] 3 3 3

[1] 3

**Creating more than 3 dimensions like 4, 5 and etc**

In [11]:
ar <- array(1:36, dim = c(3,2,2,3)) # 4 dimensional array
dim(ar)
length(dim(ar))
arr <- array(1:36, dim = c(3,2,2,3,1)) # 5 dimensional array
dim(arr)
length(dim(arr))

[1] 3 2 2 3

[1] 4

[1] 3 2 2 3 1

[1] 5

##### Vector and Matrix Operations

![Imgur](https://i.imgur.com/HmnOp1F.png)

![Imgur](https://i.imgur.com/xe79KhH.png)

#### data frame    

* unlike a matrix, a data frame can mix data types across columns

In [46]:
Name <- c("a1", "a2", "b3")
Value1 <- c(23, 4, 12)
Value2 <- c(1,45,5)
dat <- data.frame(Name, Value1, Value2)
dat

Name Value1 Value2
1 a1   23      1    
2 a2    4     45    
3 b3   12      5

##### using cbind and rbind
(to use for a data frame)

In [27]:
df <- data.frame(x = 1:3, y = c("a", "b", "c"))
df
df1 <- cbind(1,  df) 
class(df1)

x y
1 1 a
2 2 b
3 3 c

[1] "data.frame"

In [50]:
df <- data.frame(a = c(1:5), b = (1:5)^2)
df
rbind(df, c(2, 3), c(5, 6))

a b 
1 1  1
2 2  4
3 3  9
4 4 16
5 5 25

a b 
1 1  1
2 2  4
3 3  9
4 4 16
5 5 25
6 2  3
7 5  6

##### using expand.grid()  
(to create a data frame)
* The function `expand.grid` gives us all the combinations of entries of two vectors.

For example:  
all combinations of `blue and black pants` and  `white, grey and plaid shirts`

In [47]:
eg <- expand.grid(pants = c("blue", "black"), shirt = c("white", "grey", "plaid"))
class(eg)

[1] "data.frame"

In [48]:
#generate a deck of cards
suits <- c("Diamonds", "Clubs", "Hearts", "Spades")
numbers <- c("Ace", "Deuce", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Jack", "Queen", "King")
deck <- expand.grid(number=numbers, suit=suits)
class(deck)
print(deck)
deck <- paste(deck$number, deck$suit)
class(deck)
print(deck)

[1] "data.frame"

   number     suit
1     Ace Diamonds
2   Deuce Diamonds
3   Three Diamonds
4    Four Diamonds
5    Five Diamonds
6     Six Diamonds
7   Seven Diamonds
8   Eight Diamonds
9    Nine Diamonds
10    Ten Diamonds
11   Jack Diamonds
12  Queen Diamonds
13   King Diamonds
14    Ace    Clubs
15  Deuce    Clubs
16  Three    Clubs
17   Four    Clubs
18   Five    Clubs
19    Six    Clubs
20  Seven    Clubs
21  Eight    Clubs
22   Nine    Clubs
23    Ten    Clubs
24   Jack    Clubs
25  Queen    Clubs
26   King    Clubs
27    Ace   Hearts
28  Deuce   Hearts
29  Three   Hearts
30   Four   Hearts
31   Five   Hearts
32    Six   Hearts
33  Seven   Hearts
34  Eight   Hearts
35   Nine   Hearts
36    Ten   Hearts
37   Jack   Hearts
38  Queen   Hearts
39   King   Hearts
40    Ace   Spades
41  Deuce   Spades
42  Three   Spades
43   Four   Spades
44   Five   Spades
45    Six   Spades
46  Seven   Spades
47  Eight   Spades
48   Nine   Spades
49    Ten   Spades
50   Jack   Spades
51  Queen   Spades
52   King   

[1] "character"

 [1] "Ace Diamonds"   "Deuce Diamonds" "Three Diamonds" "Four Diamonds" 
 [5] "Five Diamonds"  "Six Diamonds"   "Seven Diamonds" "Eight Diamonds"
 [9] "Nine Diamonds"  "Ten Diamonds"   "Jack Diamonds"  "Queen Diamonds"
[13] "King Diamonds"  "Ace Clubs"      "Deuce Clubs"    "Three Clubs"   
[17] "Four Clubs"     "Five Clubs"     "Six Clubs"      "Seven Clubs"   
[21] "Eight Clubs"    "Nine Clubs"     "Ten Clubs"      "Jack Clubs"    
[25] "Queen Clubs"    "King Clubs"     "Ace Hearts"     "Deuce Hearts"  
[29] "Three Hearts"   "Four Hearts"    "Five Hearts"    "Six Hearts"    
[33] "Seven Hearts"   "Eight Hearts"   "Nine Hearts"    "Ten Hearts"    
[37] "Jack Hearts"    "Queen Hearts"   "King Hearts"    "Ace Spades"    
[41] "Deuce Spades"   "Three Spades"   "Four Spades"    "Five Spades"   
[45] "Six Spades"     "Seven Spades"   "Eight Spades"   "Nine Spades"   
[49] "Ten Spades"     "Jack Spades"    "Queen Spades"   "King Spades"   


## Data Types, Class and Attributes

**R contains five classes of objects. That is:  **
    
1). Numeric- real numbers  
2). Character  
3). Integer- whole numbers  
4). Logical  
5). Complex  

**These objects can have attributes (contain metadata) such as:  **
  
1). Dimensions  
2). Class    
3). Names  
4). Length  
    
These attributes are accessed with `attribute()` function.   

* Numeric (e.g, 9, 7.2, pi)
* Characters (e.g, "apple", "red")
* Integers (e.g,, 3L, as.integer(5))
* Logical (e.g., TRUE, FALSE)
* Complex (e.g, -3-87i, 1 + 0i, 1 + 4i)


## Special values  
`NA, NULL, ±Inf and NaN`  

### NA
* NA Stands for not available
* NA is a placeholder for a missing value


In [1]:
NA + 2
sum(c(NA, 4, 6))
median(c(NA, 4, 8, 4), na.rm = TRUE)
length(c(NA, 2, 3, 4))
5 == NA
NA == NA
TRUE | NA

[1] NA

[1] NA

[1] 4

[1] 4

[1] NA

[1] NA

[1] TRUE

In [1]:
x <- c(2,NA,5,4.89,10,TRUE,6/7)
is.na(x)

[1] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE

### NULL
* The class of NULL is null and has length 0
* Does not take up any space in a vector
* The function `is.null()` can be used to detect NULL variables.

In [4]:
length(c(3, 4, NULL, 1))
sum(c(5, 1, NULL, 4))

x <- NULL
c(x, 5)

[1] 3

[1] 10

[1] 5


### Inf
* Inf is a valid `numeric` that results from calculations like division of a number by zero.
* Since Inf is a numeric, operations between Inf and a finite numeric are well-defined and comparison operators work as expected.

In [6]:
32/0
5 * Inf
Inf - 2e+10
Inf + Inf
8 < -Inf
Inf == Inf

[1] Inf

[1] Inf

[1] Inf

[1] Inf

[1] FALSE

[1] TRUE

### NaN
* Stands for not a number. 
* unknown resulsts, but it is surely not a number
* e.g like `0/0, Inf-Inf` and `Inf/Inf` result in NaN
*  Computations involving numbers and NaN always result in NaN

In [5]:
NaN + 1
exp(NaN)

[1] NaN

[1] NaN

## Coercion

### Internal (implicit) coercion

Guess what the following do without running them first    
```{r}
xx <- c(1.7, "a")
xx <- c(TRUE, 2)
xx <- c("a", TRUE)
This is called implicit coercion.
```

If the two arguments are atomic vectors of different types, one is coerced to the type of the other, the (decreasing) order of precedence being character, complex, numeric, integer, logical 

![Imgur](https://i.imgur.com/6uz95Br.jpg)

In [ ]:
c(1, FALSE)
numeric 1, 0

c("a", 1)
character "a", "1"

c(list(1), "a")
list 1, "a"

c(TRUE, 1L)
numeric 1, 1

In [17]:
vec <- c(5,7,8,9,45,-87)
print(vec)
mode(vec)
vec <- append(vec, "hello")
print(vec)
mode(vec)

[1]   5   7   8   9  45 -87


[1] "numeric"

[1] "5"     "7"     "8"     "9"     "45"    "-87"   "hello"


[1] "character"

**Similarly**   

`1 == "1"` # returns `TRUE` here 1 will get coerced into char "1" since the more flexible type here is character  
`-1 < FALSE` # returns `TRUE` here FALSE will get coerced into int 0 since the more flexible type here is integer.  
`"one" < 2` # returns `FALSE` here 2 will get coerced into char "2" since the more flexible type here is character.


### External coercion and testing objects

![Imgur](https://i.imgur.com/hYYdi9O.png)

**while testing the objects**  
Use `is.atomic()` to test if an object is either atomic vector or `is.recursive()` || `is.list()` for recursive list.     
*note:* `is.vector()` does not test if an object is a vector. Instead it returns TRUE only if the object is a vector with no attributes apart from names.  
`is.atomic()` is more suitable for testing if an object is a vector.   
`is.list()` tests whether an object is truly a list.  
`is.numeric()`, similarly, is TRUE for either integer or double vectors, but not for lists.  

In [ ]:
# Ex:  
# create a string of double-precision values
dbl_var <- c(1, 2.5, 4.5)  
dbl_var
## [1] 1.0 2.5 4.5

# placing an L after the values creates a string of integers
int_var <- c(1L, 6L, 10L)
int_var
## [1]  1  6 10

In [ ]:
#To check whether a vector is made up of integer or double values:

# identifies the vector type (double, integer, logical, or character)
typeof(dbl_var)
## [1] "double"

typeof(int_var)
## [1] "integer"

## Reshaping R Objects

### for vectors and matrices

In [6]:
vec <- 1:12 # a vector
print(vec)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12


In [7]:
mat <- matrix( vec, nrow=2) # a matrix
print(mat)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    3    5    7    9   11
[2,]    2    4    6    8   10   12


In [8]:
dim(mat) <- NULL
print(mat) # back to vector

 [1]  1  2  3  4  5  6  7  8  9 10 11 12


### for dataframes 

In [9]:
print(mtcars)

                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0   

In [10]:
ULmtcars <- unlist(mtcars) # produces a vector from the dataframe
# the atomic type of a dataframe is a list
print(ULmtcars)

   mpg1    mpg2    mpg3    mpg4    mpg5    mpg6    mpg7    mpg8    mpg9   mpg10 
 21.000  21.000  22.800  21.400  18.700  18.100  14.300  24.400  22.800  19.200 
  mpg11   mpg12   mpg13   mpg14   mpg15   mpg16   mpg17   mpg18   mpg19   mpg20 
 17.800  16.400  17.300  15.200  10.400  10.400  14.700  32.400  30.400  33.900 
  mpg21   mpg22   mpg23   mpg24   mpg25   mpg26   mpg27   mpg28   mpg29   mpg30 
 21.500  15.500  15.200  13.300  19.200  27.300  26.000  30.400  15.800  19.700 
  mpg31   mpg32    cyl1    cyl2    cyl3    cyl4    cyl5    cyl6    cyl7    cyl8 
 15.000  21.400   6.000   6.000   4.000   6.000   8.000   6.000   8.000   4.000 
   cyl9   cyl10   cyl11   cyl12   cyl13   cyl14   cyl15   cyl16   cyl17   cyl18 
  4.000   6.000   6.000   8.000   8.000   8.000   8.000   8.000   8.000   4.000 
  cyl19   cyl20   cyl21   cyl22   cyl23   cyl24   cyl25   cyl26   cyl27   cyl28 
  4.000   4.000   4.000   8.000   8.000   8.000   8.000   4.000   4.000   4.000 
  cyl29   cyl30   cyl31   cy

In [11]:
UCmtcars <- unclass(mtcars) # removes the class attribute, turning the dataframe into a
# series of vectors plus any names attributes, same as setting
# class(mtcars) <- NULL
print(UCmtcars)

$mpg
 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

$cyl
 [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4

$disp
 [1] 160.0 160.0 108.0 258.0 360.0 225.0 360.0 146.7 140.8 167.6 167.6 275.8
[13] 275.8 275.8 472.0 460.0 440.0  78.7  75.7  71.1 120.1 318.0 304.0 350.0
[25] 400.0  79.0 120.3  95.1 351.0 145.0 301.0 121.0

$hp
 [1] 110 110  93 110 175 105 245  62  95 123 123 180 180 180 205 215 230  66  52
[20]  65  97 150 150 245 175  66  91 113 264 175 335 109

$drat
 [1] 3.90 3.90 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 3.92 3.07 3.07 3.07 2.93
[16] 3.00 3.23 4.08 4.93 4.22 3.70 2.76 3.15 3.73 3.08 4.08 4.43 3.77 4.22 3.62
[31] 3.54 4.11

$wt
 [1] 2.620 2.875 2.320 3.215 3.440 3.460 3.570 3.190 3.150 3.440 3.440 4.070
[13] 3.730 3.780 5.250 5.424 5.345 2.200 1.615 1.835 2.465 3.520 3.435 3.840
[25] 3.845 1.935 2.140 1.513 3.170 2.770 3.570 

In [3]:
c(mtcars) # similar to unclass but without the attributes

$mpg
 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

$cyl
 [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4

$disp
 [1] 160.0 160.0 108.0 258.0 360.0 225.0 360.0 146.7 140.8 167.6 167.6 275.8
[13] 275.8 275.8 472.0 460.0 440.0  78.7  75.7  71.1 120.1 318.0 304.0 350.0
[25] 400.0  79.0 120.3  95.1 351.0 145.0 301.0 121.0

$hp
 [1] 110 110  93 110 175 105 245  62  95 123 123 180 180 180 205 215 230  66  52
[20]  65  97 150 150 245 175  66  91 113 264 175 335 109

$drat
 [1] 3.90 3.90 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 3.92 3.07 3.07 3.07 2.93
[16] 3.00 3.23 4.08 4.93 4.22 3.70 2.76 3.15 3.73 3.08 4.08 4.43 3.77 4.22 3.62
[31] 3.54 4.11

$wt
 [1] 2.620 2.875 2.320 3.215 3.440 3.460 3.570 3.190 3.150 3.440 3.440 4.070
[13] 3.730 3.780 5.250 5.424 5.345 2.200 1.615 1.835 2.465 3.520 3.435 3.840
[25] 3.845 1.935 2.140 1.513 3.170 2.770 3.570 2.780

$qsec
 [1] 16.46 17.02 18.61 19.44 17.02 20.22 15.84 20.00 22.90 18.30 18.90 17.40
[13] 17.60 18.00 17.98 17.82 17.42 19.47 18.52 19.90 20.01 16.87 17.30 15.41
[25] 17.05 18.90 16.70 16.90 14.50 15.50 14.60 18.60

$vs
 [1] 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1

$am
 [1] 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1

$gear
 [1] 4 4 4 3 3 3 3 4 4 4 4 3 3 3 3 3 3 4 4 4 3 3 3 3 3 4 5 5 5 5 5 4

$carb
 [1] 4 4 1 1 2 1 4 2 2 4 4 3 3 3 4 4 4 1 2 1 1 2 2 4 2 1 2 2 4 6 8 2

## siwrl Package:

In [3]:
install.packages("swirl")

also installing the dependencies 'bitops', 'RCurl'




  There is a binary version available but the source version is later:
        binary   source needs_compilation
RCurl 1.98-1.3 1.98-1.5              TRUE

  Binaries will be installed
package 'bitops' successfully unpacked and MD5 sums checked
package 'RCurl' successfully unpacked and MD5 sums checked
package 'swirl' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Administrator\AppData\Local\Temp\Rtmp44AWmj\downloaded_packages


In [4]:
library(swirl)

Warning message:
"package 'swirl' was built under R version 3.6.3"
| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.



<span style="color:red; font-family:Comic Sans MS">Sources & References</span>    
<a href="http://eriqande.github.io/rep-res-web/" target="_blank">http://eriqande.github.io/rep-res-web/</a>  
<a href="http://www.pitt.edu/~njc23/" target="_blank">http://www.pitt.edu/~njc23/</a>   
<a href="http://adv-r.had.co.nz/Data-structures.html" target="_blank">http://adv-r.had.co.nz/Data-structures.html</a>   
<a href="https://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf" target="_blank">https://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf</a>  
<a href="https://github.com/aammd/UBCadv-r/wiki/01:-Data-Structures" target="_blank">https://github.com/aammd/UBCadv-r/wiki/01:-Data-Structures</a>   

