In [3]:
# ls()
#matrix
mat <- matrix(c(2,3,5,7,8,9,12,23))
class(mat)
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 2) # automatically ncol will applied for the remaining dimensions
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 4,ncol = 2)
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 6,ncol = 2) #if the dimensions are more then we will get warning but the values are recycled (not an error)
mat
#########recycling or vectorisation
vec <- seq(1,12) #sequence from 1 to 12 by default incr =1
?seq #to get help documentation from R
vec <- seq(1,12,by=2) #generate a sequence of values increment by 2
vec
vec*2^2-5*(vec+2) #applies BODMAS rule
mat
mat*2 #multiplies each element of matrix with 2
rep("lucid", 30 ) # will repeat the value 30 times
rep(c("F","M"),5)
rep(letters[1:4],500)
rep(c("F","M"),each=5) #each element 5 times
rep(c("F","M"),each=5,times=3)##each element 5 times the entire set again prints into 3 times
sample(5) #random sample of 1 to 5 values
sample(5, 2) # 2 random numbers between 1 and 5
sample(5:10, 3) # getting 3 random values from 5 to 10
####arrays
set.seed(23) #to get same random sample again
arr <- array(sample(5:16),dim = c(2,3,2))
arr
arr*2
arr+2
######################
arr <- array(sample(5:16),dim = c(2,3,2))
arr
# ls()
#matrix
mat <- matrix(c(2,3,5,7,8,9,12,23))
class(mat)
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 2)
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 4,ncol = 2)
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 6,ncol = 2)
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 6,ncol = 2)
mat
mat <- matrix(c(2,3,5,7,8,9,12,23),nrow = 6,ncol = 2)
mat
#########recycling or vectorisation
vec <- seq(1,12)
vec
vec <- seq(1,12,by=2)
vec
?seq
pi
letters
LETTERS
vec*2
vec-2
vec+5
vec
vec*2-5*(vec+2)
vec
mat
mat*2
rep("lucid", 30 )
vec
vec*2-5*(vec+2) #applies BODMAS rule
vec*2^2-5*(vec+2) #applies BODMAS rule
rep("lucid", 30 ) # will repeat the value 30 times
rep("lucid", 30 ) # will repeat the value 30 times
rep(c("F","M"),5)
rep(letters[1:4],5)
rep(letters[1:4],500)
rep(c("F","M"),each=5)
rep(c("F","M"),5)
rep(c("F","M"),each=5,times=3)
sample(5)
sample(5)
sample(5)
sample(5, 2)
sample(5, 2)
sample(5, 2)
sample(5:10, 3)
sample(5:10, 3)
sample(5:10, 3)
####arrays
arr <- array(sample(5:16),dim = c(2,3,2))
arr
####arrays
arr <- array(sample(5:16),dim = c(2,3,2))
arr
set.seed(23)
arr <- array(sample(5:16),dim = c(2,3,2))
set.seed(23)
arr <- array(sample(5:16),dim = c(2,3,2))
set.seed(23)
arr <- array(sample(5:16),dim = c(2,3,2))
arr
######################
arr <- array(sample(5:16),dim = c(2,3,2))
arr
set.seed(23)
arr <- array(sample(5:16),dim = c(2,3,2))
arr
arr*2
arr+2
vec
vec+2
vec-2
vec*2
vec/2
vec%/%2
vec%%2
vec[3] <- 15
vec%%2
vec%%3
vec%/%3
v <- c( 2,5.5,6)
t <- c(8, 3, 4)
print(v/t)
6/3
5/3
5%/%3
17/3
17%/%3
2^3
2^4
v <- c(2,5.5,6,9)
t <- c(8,2.5,14,9)
print(v>t)
v <- c(2,5.5,6,9)
t <- c(8,2.5,14,9)
print(v == t)
v <- c(2,5.5,6,9, 32)
t <- c(8,2.5,14,9)
print(v == t)
v <- c(2,5.5,6,9, 32)
t <- c(32,2.5,14,9)
print(v == t)
v <- c(2,5.5,6,9)
t <- c(8,2.5,14,9)
print(v!=t)
v <- c(3,1,TRUE,2+3i)
t <- c(4,1,FALSE,2+3i)
print(v&t)
v <- c(3,0,TRUE,2+2i)
print(!v)
134 -> obj
obj
obj <- 123
obj
6 %in% seq(1,12)
62 %in% seq(1,12)
M = matrix( c(2,6,5,1,10,4), nrow = 2,ncol = 3,byrow = TRUE)
t = M %*% t(M)
print(t)
M
t(M)
M%*%t(M)
M[1,]
M[1,]*t(M)[,1]
sum(M[1,]*t(M)[,1])

[1] "matrix"

[,1]
[1,]  2  
[2,]  3  
[3,]  5  
[4,]  7  
[5,]  8  
[6,]  9  
[7,] 12  
[8,] 23

[,1] [,2] [,3] [,4]
[1,] 2    5    8    12  
[2,] 3    7    9    23

[,1] [,2]
[1,] 2     8  
[2,] 3     9  
[3,] 5    12  
[4,] 7    23

Warning message in matrix(c(2, 3, 5, 7, 8, 9, 12, 23), nrow = 6, ncol = 2):
“data length [8] is not a sub-multiple or multiple of the number of rows [6]”

[,1] [,2]
[1,] 2    12  
[2,] 3    23  
[3,] 5     2  
[4,] 7     3  
[5,] 8     5  
[6,] 9     7

[1]  1  3  5  7  9 11

[1] -11 -13 -15 -17 -19 -21

[,1] [,2]
[1,] 2    12  
[2,] 3    23  
[3,] 5     2  
[4,] 7     3  
[5,] 8     5  
[6,] 9     7

[,1] [,2]
[1,]  4   24  
[2,]  6   46  
[3,] 10    4  
[4,] 14    6  
[5,] 16   10  
[6,] 18   14

[1] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[10] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[19] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[28] "lucid" "lucid" "lucid"

[1] "F" "M" "F" "M" "F" "M" "F" "M" "F" "M"

[1] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
  [19] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
  [37] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
  [55] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
  [73] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
  [91] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [109] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [127] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [145] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [163] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [181] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [199] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [217] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [235] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [253] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [271] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [289] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [307] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [325] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [343] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [361] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [379] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [397] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [415] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [433] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [451] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [469] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [487] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [505] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [523] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [541] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [559] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [577] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [595] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [613] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [631] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [649] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [667] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [685] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [703] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [721] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [739] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [757] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [775] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [793] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [811] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [829] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [847] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [865] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [883] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [901] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d

[1] "F" "F" "F" "F" "F" "M" "M" "M" "M" "M"

[1] "F" "F" "F" "F" "F" "M" "M" "M" "M" "M" "F" "F" "F" "F" "F" "M" "M" "M" "M"
[20] "M" "F" "F" "F" "F" "F" "M" "M" "M" "M" "M"

[1] 2 5 3 1 4

[1] 3 4

[1] 8 7 6

, , 1

     [,1] [,2] [,3]
[1,]   11    8   13
[2,]    7   16   15

, , 2

     [,1] [,2] [,3]
[1,]   10   14    6
[2,]    9   12    5

, , 1

     [,1] [,2] [,3]
[1,]   22   16   26
[2,]   14   32   30

, , 2

     [,1] [,2] [,3]
[1,]   20   28   12
[2,]   18   24   10

, , 1

     [,1] [,2] [,3]
[1,]   13   10   15
[2,]    9   18   17

, , 2

     [,1] [,2] [,3]
[1,]   12   16    8
[2,]   11   14    7

, , 1

     [,1] [,2] [,3]
[1,]    9   13   16
[2,]    8    6   12

, , 2

     [,1] [,2] [,3]
[1,]   10    7   11
[2,]   15    5   14

[1] "matrix"

[,1]
[1,]  2  
[2,]  3  
[3,]  5  
[4,]  7  
[5,]  8  
[6,]  9  
[7,] 12  
[8,] 23

[,1] [,2] [,3] [,4]
[1,] 2    5    8    12  
[2,] 3    7    9    23

[,1] [,2]
[1,] 2     8  
[2,] 3     9  
[3,] 5    12  
[4,] 7    23

Warning message in matrix(c(2, 3, 5, 7, 8, 9, 12, 23), nrow = 6, ncol = 2):
“data length [8] is not a sub-multiple or multiple of the number of rows [6]”

[,1] [,2]
[1,] 2    12  
[2,] 3    23  
[3,] 5     2  
[4,] 7     3  
[5,] 8     5  
[6,] 9     7

Warning message in matrix(c(2, 3, 5, 7, 8, 9, 12, 23), nrow = 6, ncol = 2):
“data length [8] is not a sub-multiple or multiple of the number of rows [6]”

[,1] [,2]
[1,] 2    12  
[2,] 3    23  
[3,] 5     2  
[4,] 7     3  
[5,] 8     5  
[6,] 9     7

Warning message in matrix(c(2, 3, 5, 7, 8, 9, 12, 23), nrow = 6, ncol = 2):
“data length [8] is not a sub-multiple or multiple of the number of rows [6]”

[,1] [,2]
[1,] 2    12  
[2,] 3    23  
[3,] 5     2  
[4,] 7     3  
[5,] 8     5  
[6,] 9     7

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[1]  1  3  5  7  9 11

[1] 3.141593

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1]  2  6 10 14 18 22

[1] -1  1  3  5  7  9

[1]  6  8 10 12 14 16

[1]  1  3  5  7  9 11

[1] -13 -19 -25 -31 -37 -43

[1]  1  3  5  7  9 11

[,1] [,2]
[1,] 2    12  
[2,] 3    23  
[3,] 5     2  
[4,] 7     3  
[5,] 8     5  
[6,] 9     7

[,1] [,2]
[1,]  4   24  
[2,]  6   46  
[3,] 10    4  
[4,] 14    6  
[5,] 16   10  
[6,] 18   14

[1] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[10] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[19] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[28] "lucid" "lucid" "lucid"

[1]  1  3  5  7  9 11

[1] -13 -19 -25 -31 -37 -43

[1] -11 -13 -15 -17 -19 -21

[1] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[10] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[19] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[28] "lucid" "lucid" "lucid"

[1] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[10] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[19] "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid" "lucid"
[28] "lucid" "lucid" "lucid"

[1] "F" "M" "F" "M" "F" "M" "F" "M" "F" "M"

[1] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c"
[20] "d"

[1] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
  [19] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
  [37] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
  [55] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
  [73] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
  [91] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [109] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [127] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [145] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [163] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [181] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [199] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [217] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [235] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [253] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [271] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [289] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [307] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [325] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [343] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [361] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [379] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [397] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [415] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [433] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [451] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [469] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [487] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [505] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [523] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [541] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [559] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [577] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [595] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [613] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [631] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [649] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [667] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [685] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [703] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [721] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [739] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [757] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [775] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [793] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [811] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [829] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [847] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [865] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b"
 [883] "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d"
 [901] "a" "b" "c" "d" "a" "b" "c" "d" "a" "b" "c" "d

[1] "F" "F" "F" "F" "F" "M" "M" "M" "M" "M"

[1] "F" "M" "F" "M" "F" "M" "F" "M" "F" "M"

[1] "F" "F" "F" "F" "F" "M" "M" "M" "M" "M" "F" "F" "F" "F" "F" "M" "M" "M" "M"
[20] "M" "F" "F" "F" "F" "F" "M" "M" "M" "M" "M"

[1] 2 4 3 5 1

[1] 4 3 1 5 2

[1] 2 4 1 5 3

[1] 1 4

[1] 1 2

[1] 4 5

[1] 9 5 6

[1]  6  8 10

[1] 9 6 8

, , 1

     [,1] [,2] [,3]
[1,]   15    7    9
[2,]    5   13   11

, , 2

     [,1] [,2] [,3]
[1,]    6   12   16
[2,]   14   10    8

, , 1

     [,1] [,2] [,3]
[1,]    6    9   14
[2,]   15   13   10

, , 2

     [,1] [,2] [,3]
[1,]   11    5   16
[2,]    7    8   12

, , 1

     [,1] [,2] [,3]
[1,]   11    8   13
[2,]    7   16   15

, , 2

     [,1] [,2] [,3]
[1,]   10   14    6
[2,]    9   12    5

, , 1

     [,1] [,2] [,3]
[1,]    9   13   16
[2,]    8    6   12

, , 2

     [,1] [,2] [,3]
[1,]   10    7   11
[2,]   15    5   14

, , 1

     [,1] [,2] [,3]
[1,]   11    8   13
[2,]    7   16   15

, , 2

     [,1] [,2] [,3]
[1,]   10   14    6
[2,]    9   12    5

, , 1

     [,1] [,2] [,3]
[1,]   22   16   26
[2,]   14   32   30

, , 2

     [,1] [,2] [,3]
[1,]   20   28   12
[2,]   18   24   10

, , 1

     [,1] [,2] [,3]
[1,]   13   10   15
[2,]    9   18   17

, , 2

     [,1] [,2] [,3]
[1,]   12   16    8
[2,]   11   14    7

[1]  1  3  5  7  9 11

[1]  3  5  7  9 11 13

[1] -1  1  3  5  7  9

[1]  2  6 10 14 18 22

[1] 0.5 1.5 2.5 3.5 4.5 5.5

[1] 0 1 2 3 4 5

[1] 1 1 1 1 1 1

[1] 1 1 1 1 1 1

[1] 1 0 0 1 0 2

[1] 0 1 5 2 3 3

[1] 0.250000 1.833333 1.500000


[1] 2

[1] 1.666667

[1] 1

[1] 5.666667

[1] 5

[1] 8

[1] 16

[1] FALSE  TRUE FALSE FALSE
[1] FALSE FALSE FALSE  TRUE


Warning message in v == t:
“longer object length is not a multiple of shorter object length”

[1] FALSE FALSE FALSE  TRUE FALSE


Warning message in v == t:
“longer object length is not a multiple of shorter object length”

[1] FALSE FALSE FALSE  TRUE  TRUE
[1]  TRUE  TRUE  TRUE FALSE
[1]  TRUE  TRUE FALSE  TRUE
[1] FALSE  TRUE FALSE FALSE


[1] 134

[1] 123

[1] TRUE

[1] FALSE

In [2]:
################# control structures #########################
x <- -14
if (x>=0)
  print(paste("the output is",x) )

if (x<=0)
  print(paste("the output is",x) )

###############

num1 <- 10
num2 <- 20

if(num1<=num2){
  print("Num1 is less or equal to Num2")
}
#################if else###########

x <- 1:15
if (sample(x, 1) <= 10) {
  print("x is less than 10")
} else {
  print("x is greater than 10")
}

x <- 1:15
x1 <- sample(x, 1)
if (x1 <= 10) {
  print(paste("x is less than 10, and the sample value is", x1))
} else {
  print(paste("x is greater than 10, and the sample value is", x1))
}

x <- 1:15
set.seed(23) # to get same sample every time when you run the script
x1 <- sample(x, 1)
if (x1 <= 10) {
  print(paste("x is less than 10, and the sample value is", x1))
  print("if block")
} else {
  print(paste("x is greater than 10, and the sample value is", x1))
  print("else block")
  }

##########if else in another way ##################

x <- 1:15
x <- sample(x,1)
ifelse(x <= 10, "x less than 10", "x greater than 10")

x <- 1:15
x <- sample(x,1)
ifelse(x <= 10, paste("x less than 10", x), paste("x greater than 10", x))

##########
cat("hello world", "hai") #cat function is to concatenate and print statements to the console
?cat
x <- 1:15
x <- sample(x,1)
ifelse(x <= 10, print(paste("x less than 10", x)), paste("x greater than 10", x))
####################  how to use paste and cat functions #########
# print("hello", "world")#error
print(paste("hello", "world"))# to concatenate strings
cat("hello", "world")# alternative to above statement
########## if else if #######################
x <- c("what","is","truth")

if("Truth" %in% x) {
  print("Truth is found the this time-block 1")
} else if ("truth" %in% x) {
  print("truth is found the this time-block 2")
} else {
  print("No truth found")  # if above both statements are false
}
############## for loop###########################

vector <- c("aaa","bbb","ccc")
for(i in vector){   
  print(i)   
}

for(bb in letters)
{
  print(bb)
}

########### script using  curly braces 
l <- sample(letters[1:3],1)
l
if (l=="a")
{
  print(paste("a",l))
}else if(l=="b")
{
  print(paste("b",l))
}else if (l=="c")
{
  print(paste("c",l))
}
##################### with out curly braces ###########

l <- sample(letters[1:3],1)
l
if (l=="a")
  print(paste("a",l)) else
  if(l=="b")
  print(paste("b",l)) else
  if (l=="c")
  print(paste("c",l))

[1] "the output is -14"
[1] "Num1 is less or equal to Num2"
[1] "x is greater than 10"
[1] "x is less than 10, and the sample value is 7"
[1] "x is less than 10, and the sample value is 9"
[1] "if block"


[1] "x less than 10"

[1] "x less than 10 5"

hello world hai

[1] "x greater than 10 11"

[1] "hello world"
hello world[1] "truth is found the this time-block 2"
[1] "aaa"
[1] "bbb"
[1] "ccc"
[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"
[1] "f"
[1] "g"
[1] "h"
[1] "i"
[1] "j"
[1] "k"
[1] "l"
[1] "m"
[1] "n"
[1] "o"
[1] "p"
[1] "q"
[1] "r"
[1] "s"
[1] "t"
[1] "u"
[1] "v"
[1] "w"
[1] "x"
[1] "y"
[1] "z"


[1] "c"

[1] "c c"


[1] "b"

[1] "b b"


In [2]:
vector <- c("aaa","bbb","ccc")
for(i in vector){   #for loop to print the vector elements
  print(i)   
}

for(i in letters){   #for loop to print the alphabets from vector letters
  print(i)   
}

for(i in month.name){   # for loop to print each month full names 
  print(i)   
}


for(i in month.abb){   # for loop to print each month abbreviated names
  print(i)   
}

apropos('month') # to get pattern matching related functions
apropos("day") 
apropos("week") 
?weekdays

for(i in 2:5){
  z <- i +1
  print(z)
}

x <- c('a', 'b', 'c', 'd')
seq_along(x)  # seq_along gives the serial element counts of the vector
seq_along(month.abb)
seq_along(letters)
seq_along(seq(1,13,by=3))
seq_along(rep("hello",30))

x <- c('a', 'b', 'c', 'd')
# x <- letters
for (i in seq_along(x)){  
  print(x[i])                #printing through indexing value
}

for (i in seq_along(x)){  
  print(i)                # printing through only indexing number
}

for (words in x){
  print(words)
}

mymat <- matrix(1:9,3,3)
mymat

mymat <- matrix(1:900,300,3)  
mymat

for (i in seq_len(nrow(mymat))){       #seq_len will takes length as input
  for (j in seq_len(ncol(mymat))){      
    print(mymat[i,j])
  }
}

head(women)# to get first 6 observations 
nrow(women)  # to get number of observation(rows)
ncol(women)  # to get number of variables(columns)
dim(women)   # to get rows and columns (dimensions)
x <- head(women,10) # taking x as only first 10 women heights and weights
x
data() # to get default datasets which are present in R 
?iris  # to get the documentation of iris dataset
mrnull <- NULL # taking an empty single value vector
for(i in seq_along(x[,1])){
  concat <- c(mrnull, mean(as.numeric(x[i, 1:2]))) #finding average between each women height and weight
  print(concat)
}
str(women) # to check the structure of women dataset
#View(women) # to view the dataset 

############ while loop ###################################
i <- 1

while (i < 6) {    #iterates the loop until the condition is false
  print(i)
  i = i+1
}

i <- 1
if (i < 6) {      #enter into the block if the condition is true
  print(i)
  i = i+1
}

[1] "aaa"
[1] "bbb"
[1] "ccc"
[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"
[1] "f"
[1] "g"
[1] "h"
[1] "i"
[1] "j"
[1] "k"
[1] "l"
[1] "m"
[1] "n"
[1] "o"
[1] "p"
[1] "q"
[1] "r"
[1] "s"
[1] "t"
[1] "u"
[1] "v"
[1] "w"
[1] "x"
[1] "y"
[1] "z"
[1] "January"
[1] "February"
[1] "March"
[1] "April"
[1] "May"
[1] "June"
[1] "July"
[1] "August"
[1] "September"
[1] "October"
[1] "November"
[1] "December"
[1] "Jan"
[1] "Feb"
[1] "Mar"
[1] "Apr"
[1] "May"
[1] "Jun"
[1] "Jul"
[1] "Aug"
[1] "Sep"
[1] "Oct"
[1] "Nov"
[1] "Dec"


[1] "month.abb"     "month.name"    "monthplot"     "months"       
[5] "months.Date"   "months.POSIXt" "sunspot.month"

[1] "pbirthday"       "qbirthday"       "weekdays"        "weekdays.Date"  
[5] "weekdays.POSIXt"

[1] "weekdays"        "weekdays.Date"   "weekdays.POSIXt"

[1] 3
[1] 4
[1] 5
[1] 6


[1] 1 2 3 4

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26

[1] 1 2 3 4 5

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] 1
[1] 2
[1] 3
[1] 4
[1] "a"
[1] "b"
[1] "c"
[1] "d"


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
 [1,]  1   301  601 
 [2,]  2   302  602 
 [3,]  3   303  603 
 [4,]  4   304  604 
 [5,]  5   305  605 
 [6,]  6   306  606 
 [7,]  7   307  607 
 [8,]  8   308  608 
 [9,]  9   309  609 
[10,] 10   310  610 
[11,] 11   311  611 
[12,] 12   312  612 
[13,] 13   313  613 
[14,] 14   314  614 
[15,] 15   315  615 
[16,] 16   316  616 
[17,] 17   317  617 
[18,] 18   318  618 
[19,] 19   319  619 
[20,] 20   320  620 
[21,] 21   321  621 
[22,] 22   322  622 
[23,] 23   323  623 
[24,] 24   324  624 
[25,] 25   325  625 
[26,] 26   326  626 
[27,] 27   327  627 
[28,] 28   328  628 
[29,] 29   329  629 
[30,] 30   330  630 
[31,] ...  ...  ... 
[32,] 271  571  871 
[33,] 272  572  872 
[34,] 273  573  873 
[35,] 274  574  874 
[36,] 275  575  875 
[37,] 276  576  876 
[38,] 277  577  877 
[39,] 278  578  878 
[40,] 279  579  879 
[41,] 280  580  880 
[42,] 281  581  881 
[43,] 282  582  882 
[44,] 283  583  883 
[45,] 284  584  884 
[46,] 285  585  885 
[47,] 286  586  886 
[48,] 287  587  887 
[49,] 288  588  888 
[50,] 289  589  889 
[51,] 290  590  890 
[52,] 291  591  891 
[53,] 292  592  892 
[54,] 293  593  893 
[55,] 294  594  894 
[56,] 295  595  895 
[57,] 296  596  896 
[58,] 297  597  897 
[59,] 298  598  898 
[60,] 299  599  899 
[61,] 300  600  900

[1] 1
[1] 301
[1] 601
[1] 2
[1] 302
[1] 602
[1] 3
[1] 303
[1] 603
[1] 4
[1] 304
[1] 604
[1] 5
[1] 305
[1] 605
[1] 6
[1] 306
[1] 606
[1] 7
[1] 307
[1] 607
[1] 8
[1] 308
[1] 608
[1] 9
[1] 309
[1] 609
[1] 10
[1] 310
[1] 610
[1] 11
[1] 311
[1] 611
[1] 12
[1] 312
[1] 612
[1] 13
[1] 313
[1] 613
[1] 14
[1] 314
[1] 614
[1] 15
[1] 315
[1] 615
[1] 16
[1] 316
[1] 616
[1] 17
[1] 317
[1] 617
[1] 18
[1] 318
[1] 618
[1] 19
[1] 319
[1] 619
[1] 20
[1] 320
[1] 620
[1] 21
[1] 321
[1] 621
[1] 22
[1] 322
[1] 622
[1] 23
[1] 323
[1] 623
[1] 24
[1] 324
[1] 624
[1] 25
[1] 325
[1] 625
[1] 26
[1] 326
[1] 626
[1] 27
[1] 327
[1] 627
[1] 28
[1] 328
[1] 628
[1] 29
[1] 329
[1] 629
[1] 30
[1] 330
[1] 630
[1] 31
[1] 331
[1] 631
[1] 32
[1] 332
[1] 632
[1] 33
[1] 333
[1] 633
[1] 34
[1] 334
[1] 634
[1] 35
[1] 335
[1] 635
[1] 36
[1] 336
[1] 636
[1] 37
[1] 337
[1] 637
[1] 38
[1] 338
[1] 638
[1] 39
[1] 339
[1] 639
[1] 40
[1] 340
[1] 640
[1] 41
[1] 341
[1] 641
[1] 42
[1] 342
[1] 642
[1] 43
[1] 343
[1] 643
[1] 44
[1] 344
[1] 6

height weight
1 58     115   
2 59     117   
3 60     120   
4 61     123   
5 62     126   
6 63     129

[1] 15

[1] 2

[1] 15  2

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142

[1] 86.5
[1] 88
[1] 90
[1] 92
[1] 94
[1] 96
[1] 98
[1] 100
[1] 102.5
[1] 104.5
'data.frame':	15 obs. of  2 variables:
 $ height: num  58 59 60 61 62 63 64 65 66 67 ...
 $ weight: num  115 117 120 123 126 129 132 135 139 142 ...
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 1
