# Types of Operators

Arithmetic Operators  `(+  -  *  /  %%  %/%  ^)`  
Relational Operators`(>  <  <=  >=  ==  !=  )`         
Logical Operators   `(&  |  !  &&  ||)`  
Assignment Operators `(<−  =  <<−  ->  ->>)`  
Miscellaneous Operators `(:  %in%  %*%)`

![Imgur](https://i.imgur.com/rJyfhp3.png)

## Vectorization or recycling 

In [1]:
vect1 <- c(4,6,-78,56,23)
vect2 <- c(14,26,-7,5,3)
vect3 <- c(14,26,-7,5,3,9,10)
vect1 + vect2
vect1 - vect2
vect1 + vect3  # recycled the process bcz of different lengths

[1]  18  32 -85  61  26

[1] -10 -20 -71  51  20

Warning message in vect1 + vect3:
“longer object length is not a multiple of shorter object length”

[1]  18  32 -85  61  26  13  16

In [2]:
# Divide the first vector with the second

v <- c( 2,5.5,6)
t <- c(8, 3, 4)
print(v/t) # will get actual quotient

[1] 0.250000 1.833333 1.500000


In [3]:
v <- c( 2,5.5,6)
t <- c(8, 3, 4)
print(v%/%t)  # ignore decimal part

[1] 0 1 1


In [4]:
# Give the remainder of the first vector with the second
v <- c( 2,5.5,6)
t <- c(8, 3, 4)
print(v%%t)

[1] 2.0 2.5 2.0


In [5]:
# This operator is used to identify if an element belongs to a vector
v1 <- 8
v2 <- 12
t <- 1:10
print(v1 %in% t) 
print(v2 %in% t) 

[1] TRUE
[1] FALSE


## Logical AND (`&&`) and Logical OR (`||`)

In [6]:
# Called Logical AND operator. Takes first element of both the vectors and gives the TRUE only if both are TRUE.
v <- c(3,0,TRUE,2+2i)
t <- c(1,3,TRUE,2+3i)
print(v&&t)

[1] TRUE


In [7]:
# Called Logical OR operator. Takes first element of both the vectors and gives the TRUE if one of them is TRUE.
v <- c(0,0,TRUE,2+2i)
t <- c(0,3,TRUE,2+3i)
print(v||t)

[1] FALSE


## `%in%` Operator

In [8]:
# This operator is used to identify if an element belongs to a vector.

v1 <- 8
v2 <- 12
t <- 1:10
print(v1 %in% t) 
print(v2 %in% t)

[1] TRUE
[1] FALSE


# Control Structures or Conditional Statements

### If Condition
**IF statement associates a condition with a sequence of statements, The sequence of statements is executed only if the condition is true. If the condition is false or null, the IF statement does nothing. In either case, control passes to the next statement**

In [2]:
num1=10
num2=20
 
if(num1<=num2){
print("Num1 is less or equal to Num2")
    }

[1] "Num1 is less or equal to Num2"


### If..Else

In [3]:
x <- 1:15
if (sample(x, 1) <= 10) {
    print("x is less than 10")
} else {
    print("x is greater than 10")
}

[1] "x is less than 10"


**Another way in R**

In [4]:
x <- 1:15
ifelse(x <= 10, "x less than 10", "x greater than 10")

[1] "x less than 10"    "x less than 10"    "x less than 10"   
 [4] "x less than 10"    "x less than 10"    "x less than 10"   
 [7] "x less than 10"    "x less than 10"    "x less than 10"   
[10] "x less than 10"    "x greater than 10" "x greater than 10"
[13] "x greater than 10" "x greater than 10" "x greater than 10"

### If...Else...If

In [4]:
if (10==10)
    print('10 is equal to 10') else
    print('invalid')

[1] "10 is equal to 10"


In [5]:
x <- 3
y <- if(x>2){0}else{1}
y

[1] 0

In [6]:
z <- 1:10
ifelse(z<2 | z>8, 1, 0)

[1] 1 0 0 0 0 0 0 0 1 1

In [7]:
ifelse(z>5,'TRUE','FALSE')

[1] "FALSE" "FALSE" "FALSE" "FALSE" "FALSE" "TRUE"  "TRUE"  "TRUE"  "TRUE" 
[10] "TRUE"

In [8]:
z <- 1:10
ifelse(z>4&z>8,"x","?")

[1] "?" "?" "?" "?" "?" "?" "?" "?" "x" "x"

In [5]:
x <- c("what","is","truth")

if("Truth" %in% x) {
   print("Truth is found the first time")
} else if ("truth" %in% x) {
   print("truth is found the second time")
} else {
   print("No truth found")
}

[1] "truth is found the second time"


## For and While

### For Loop
To repeats a statement or group of for a fixed number of times.

In [6]:
vector <- c("aaa","bbb","ccc")
 for(i in vector){   
   print(i)   
}    

[1] "aaa"
[1] "bbb"
[1] "ccc"


In [5]:
for (year in c(2010,2011,2012,2013,2014,2015)){
  print(paste("The year is", year))
}

[1] "The year is 2010"
[1] "The year is 2011"
[1] "The year is 2012"
[1] "The year is 2013"
[1] "The year is 2014"
[1] "The year is 2015"


In [9]:
for(i in 2:5){
    z <- i +1
    print(z)
}

[1] 3
[1] 4
[1] 5
[1] 6


| Instead of  | Use          |
|-------------|--------------|
| 1:length(x) | seq_along(x) |
| 1:n         | seq_len(n)   |

In [14]:
x <- c('a', 'b', 'c', 'd')
for (i in seq_along(x)){
    print(x[i])
}

#alternatively
for (words in x){
    print(words)
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "a"
[1] "b"
[1] "c"
[1] "d"


In [15]:
mymat <- matrix(1:9,3,3)
mymat

for (i in seq_len(nrow(mymat))){
    for (j in seq_len(ncol(mymat))){
        print(mymat[i,j])
    }
}

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 1
[1] 4
[1] 7
[1] 2
[1] 5
[1] 8
[1] 3
[1] 6
[1] 9


In [22]:
x <- head(women,10)
x
mrnull <- NULL
for(i in seq_along(x[,1])){
    concat <- c(mrnull, mean(as.numeric(x[i, 1:2])))
    print(concat)
}


height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142

[1] 86.5
[1] 88
[1] 90
[1] 92
[1] 94
[1] 96
[1] 98
[1] 100
[1] 102.5
[1] 104.5


In [2]:
# Create your three-dimensional array
my_array <- array(1:20, dim=c(20, 20, 20))

for (i in 1:dim(my_array)[1]) {
  for (j in 1:dim(my_array)[2]) {
    for (k in 1:dim(my_array)[3]) {
      my_array[i,j,k] = i*j*k
    }
  }
}

# Show a 10x10x15 chunk of your array
print(my_array[1:10, 1:10, 1:15])

, , 1

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    1    2    3    4    5    6    7    8    9    10
 [2,]    2    4    6    8   10   12   14   16   18    20
 [3,]    3    6    9   12   15   18   21   24   27    30
 [4,]    4    8   12   16   20   24   28   32   36    40
 [5,]    5   10   15   20   25   30   35   40   45    50
 [6,]    6   12   18   24   30   36   42   48   54    60
 [7,]    7   14   21   28   35   42   49   56   63    70
 [8,]    8   16   24   32   40   48   56   64   72    80
 [9,]    9   18   27   36   45   54   63   72   81    90
[10,]   10   20   30   40   50   60   70   80   90   100

, , 2

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    2    4    6    8   10   12   14   16   18    20
 [2,]    4    8   12   16   20   24   28   32   36    40
 [3,]    6   12   18   24   30   36   42   48   54    60
 [4,]    8   16   24   32   40   48   56   64   72    80
 [5,]   10   20   30   40   50   60   70   80   90   100
 [6,]   12   24 

### While Loop
Loop until a specific condition is met

In [7]:
i <- 1

while (i < 6) {
   print(i)
   i = i+1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [3]:
a <- 0
b <- 1
print(a)
while (b < 50) {
    print(b)
    temp <- a + b
    a <- b
    b <- temp
}

[1] 0
[1] 1
[1] 1
[1] 2
[1] 3
[1] 5
[1] 8
[1] 13
[1] 21
[1] 34


In [4]:
a <- 0
b <- 1
print(a)
while (b < 50) {
     print(b)
     temp <- a + b
     a <- b
     b <- temp
}

[1] 0
[1] 1
[1] 1
[1] 2
[1] 3
[1] 5
[1] 8
[1] 13
[1] 21
[1] 34


## repeat break and next

### Repeat statement
Iterate over a block of code multiple number of times.

In [8]:
x <- 1

repeat {
   print(x)
   x = x+1
   if (x == 6){
       break
   }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


### Break Statement
break is used inside any loop like `repeat`, `for` or `while` to stop the iterations and flow the control outside of the loop.

In [9]:
x <- 1:5

for (val in x) {
    if (val == 3){
        break
    }
    print(val)
}

[1] 1
[1] 2


In [23]:
x <- 1:10
for (num in x){
    if (num==6) break
    mynum <- paste(num, "and so on. ", sep = " ")
    print(mynum)
}

[1] "1 and so on. "
[1] "2 and so on. "
[1] "3 and so on. "
[1] "4 and so on. "
[1] "5 and so on. "


### Next Statment
* Useful to controls the flow of R loops  
* generaal usage inside the For Loop and While Loop  

**Example:**

In [13]:
x <- 1:5

for (val in x) {
    if (val == 3){
        next
    }
    print(val)
}

[1] 1
[1] 2
[1] 4
[1] 5


In [6]:
m=20
odd=numeric()

for (k in 1:m) {
   if (!k %% 2)
      next
      odd <- c(odd,k)
}
odd

[1]  1  3  5  7  9 11 13 15 17 19

In [7]:
for (i in 1:10) {
  if (!i %% 2){
    next
  }
    print(i)
}

[1] 1
[1] 3
[1] 5
[1] 7
[1] 9


In [24]:
x <- 1:10
for (num in x){
    if (num %% 3 == 1) next
    mynum <- paste(num, "and so on. ", sep = " ")
    print(mynum)
}

[1] "2 and so on. "
[1] "3 and so on. "
[1] "5 and so on. "
[1] "6 and so on. "
[1] "8 and so on. "
[1] "9 and so on. "


### Switch...Case Statment
**switch statement allows a variable to be tested for equality against a list of values. Each value is called a case**  

Syntax:
```r
switch (Expression, "Option 1", "Option 2", "Option 3", ....., "Option N") 
```

**Example:**

In [12]:
number1 <- 30
number2 <- 20
operator <- readline(prompt="Please enter any ARITHMETIC OPERATOR You wish!: ")
 
switch(operator,
       "+" = print(paste("Addition of two numbers is: ", number1 + number2)),
       "-" = print(paste("Subtraction of two numbers is: ", number1 - number2)),
       "*" = print(paste("Multiplication of two numbers is: ", number1 * number2)),
       "^" = print(paste("Exponent of two numbers is: ", number1 ^ number2)),
       "/" = print(paste("Division of two numbers is: ", number1 / number2)),
       "%/%" = print(paste("Integer Division of two numbers is: ", number1 %/% number2)),
       "%%" = print(paste("Division of two numbers is: ", number1 %% number2))
)

[1] "Multiplication of two numbers is:  600"


## Conclusion        
**Loops are not recommended until and unless its really needed, since R has vectorisation feature**

In [14]:
# let us take a vector 
vect <- c(1,2,3,4,5,6,7,9)
# now we multiply each element of vect with 5
print(vect * 5)
# now we add each element of vect with 5
print(vect + 5)
# now we subtract each element of vect with 5
print(vect - 5)

[1]  5 10 15 20 25 30 35 45
[1]  6  7  8  9 10 11 12 14
[1] -4 -3 -2 -1  0  1  2  4
