In [1]:
rm(list = ls()) # to remove all the objects from current session

##### vector ########
vNumeric <- c(2,7,9,38,-56,7,12)
mode(vNumeric)
vChar <- c("lucid", "IT", "solutions")
mode(vChar)
vComp <- c(2+3i, 8-7i, 12-90i,-3-42i)
mode(vComp)

?sum
sum(1, 2, 3, 4, 5) # to sum/total the values present in the function
v <- 4:90 # storing the values from 4 to 90 sequentially
v[81] # to get 81st position value

vLogical <- c(TRUE,FALSE,TRUE,FALSE)
vInteger <- c(34,56,76,12)
vInteger <- c(34L,56L,76L,12L)
mode(vInteger)
class(vInteger)
is.double(23.56)
is.double(23)
############### vector indexing ############
vChar[2] # print 2nd element
vChar[c(2,3)] # print 2nd and 3rd
vChar[-c(2,3)] # print excepot 2nd and 3rd
rVect <- 5:30
rVect
rVect[4:8] # sequential data
############### matrix  ##############
mat <- matrix(1:12, nro = 3, ncol = 4)
print(mat)
mat
dim(mat)
############ indexing of matrix ##############
mat[,] # total matrix :blank means all (no restriction) 
mat
mat[2,] # total matrix : only print 2nd row
mat[,2] # total matrix : only print 2nd column as vector format
mat[,2,drop=FALSE] # total matrix : only print 2nd column as matrix format
mat[1,2] # single value at 1st row and 2nd column
mat[,c(2,3)] # 2nd column and 3rd column at a time
mat[,-c(2,3)] # except 2nd column and 3rd column at a time
diag(mat)
x <- vector()
x
x <- vector(length = 10)
x
vector("character", length = 10)
x <- 1:10
x
############# vector coersion (internal) #################
# logical -> integer -> numeric -> complex -> character.
vect <- c(2L,TRUE)
class(vect)
vect <- c(2L,TRUE, 34)
class(vect)
vect <- c(2L,TRUE, 34, 4-6i)
class(vect)
vect <- c(2L,TRUE, 34, 4-6i, "lucid")
class(vect)
vect <- c(2L,TRUE, 4-6i)
class(vect)

########### external coersion #########

vect
TRUE == 1
TRUE + 20 # true always one
FALSE -1 # false always zero

TRUE*167
FALSE*89
!FALSE - 43
!-43
(!FALSE) - 43

########## vector operations
vect <- seq(from = 3,to = 23,by=2)
vect
min(vect) # minimum value
max(vect) # max value
which.max(vect)
which.min(vect)
vect <- sample(vect) # to get any random sample value
vect
which.max(vect)  # location of maximum value presented
which.min(vect) # location of the minimum value presented
sum(vect) # total summation
sort(vect) # sorting the values from min to max
sort(vect,decreasing = TRUE) # sorting the values from max to min
vect
vect[vect==13]

append(vect,78)
append(vect,c(78,40))
vect
rev(vect)
vect[-3]
unique(vect)
rep(c(23,45),4)
?rep


[1] "numeric"

[1] "character"

[1] "complex"

[1] 15

[1] 84

[1] "numeric"

[1] "integer"

[1] TRUE

[1] TRUE

[1] "IT"

[1] "IT"        "solutions"

[1] "lucid"

[1]  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
[26] 30

[1]  8  9 10 11 12

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 3 4

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1]  2  5  8 11

[1] 4 5 6

[,1]
[1,] 4   
[2,] 5   
[3,] 6

[1] 4

[,1] [,2]
[1,] 4    7   
[2,] 5    8   
[3,] 6    9

[,1] [,2]
[1,] 1    10  
[2,] 2    11  
[3,] 3    12

[1] 1 5 9

logical(0)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

[1] "" "" "" "" "" "" "" "" "" ""

[1]  1  2  3  4  5  6  7  8  9 10

[1] "integer"

[1] "numeric"

[1] "complex"

[1] "character"

[1] "complex"

[1] 2+0i 1+0i 4-6i

[1] TRUE

[1] 21

[1] -1

[1] 167

[1] 0

[1] FALSE

[1] FALSE

[1] -42

[1]  3  5  7  9 11 13 15 17 19 21 23

[1] 3

[1] 23

[1] 11

[1] 1

[1] 21 15 23  3 17  7  9  5 13 19 11

[1] 3

[1] 4

[1] 143

[1]  3  5  7  9 11 13 15 17 19 21 23

[1] 23 21 19 17 15 13 11  9  7  5  3

[1] 21 15 23  3 17  7  9  5 13 19 11

[1] 13

[1] 21 15 23  3 17  7  9  5 13 19 11 78

[1] 21 15 23  3 17  7  9  5 13 19 11 78 40

[1] 21 15 23  3 17  7  9  5 13 19 11

[1] 11 19 13  5  9  7 17  3 23 15 21

[1] 21 15  3 17  7  9  5 13 19 11

[1] 21 15 23  3 17  7  9  5 13 19 11

[1] 23 45 23 45 23 45 23 45

In [5]:
# to check current working directory
# getwd()
#setting a working directory
#setwd("E:/DSwRandP-Apr18/R-basics")
#data types

#integers
vecI<- c(1+2L)
vecI1 <- seq(2,6)
class(vecI1)


#numeric
vecN <- c(2,3,5,6)
class(vecN)
#character
vecC <- c("1+2i", "TRUE", "lucid", "23")
class(vecC)
#logical
vecL<- c(TRUE,FALSE,TRUE,FALSE)
class(vecL)
#complex
vecCom <- c(2+3i, 9-0i, -78-34i)
class(vecCom)
#data structure

#vector (1 dimentional storage of elements)
# integer vector
intVec <- c(TRUE,5L,90L,65L, "yes")
class(intVec)
numVec <- c(3,5,90,65, "lucid")
class(numVec)
charVec <- c("rajesh", "ramesh", "suresh", "90")
class(charVec)
compVec <- c(2+4i, "9+6i", -2+56i, -4-45i)
class(compVec)
logiVec <- c(12,FALSE, TRUE, TRUE)
class(logiVec)
sum(3,4)


# subsetting or indexing
intVec[3] # accessing 3rd element
intVec[-3] #ignoring only 3rd element
intVec[c(2,4)]
intVec[2:4]
intVec[-(2:4)]
intVec[-c(2:4)]
intVec[c(2,4)] <- c(678,45)
intVec

myVec <- seq(1,12)
class(myVec)
myVec
myVec[seq(4,9)]
myVec[c(4,9)]
1:12
myVec[myVec==5]
myVec <- c(12,34,56,67,83)
myVec[myVec==c(12,56)]
myVec <- seq(1,5)
myVec[1:12]
#matrix (2 dimensional storage of elemtns)
myMat <- matrix(1:12, 3, 4)
#?matrix
myMat
dim(myMat)
# dim(myMat) <- c(1,12)
#View(myMat)
print(myMat)
# view(myMat)
# View(myMat)
# indexing of matrix
#myMat[2,3]
myMat[2,]
#myMat[,c(1,3)]
myMat[,2:4]
myMat[,rep(3,2)]
myMat[,rep(3,2)]
myMat[,seq(1,3)][2,2]
myMat[2,2]
myMat[rep(3,2),]
#arrays
myArr <- array(1:12)
dim(myArr) <- c(2,3,2)
myArr
myArr <- array(1:12,dim = c(4,3,2))
#View(myArr)
print(myArr)
# indexing of arrays
myArr[,,2]
myArr[,2,2]
myArr[1,2,2]
myArr[1,2,] <- c(23,45)
myArr[1,2,] 
myArr[1,2,] <- rep(23,2)
#data frame
# creating data frame
df <- data.frame(empno=c(23L,-92L,50L),
                 empname=c("ramesh", "rajesh", "suresh"),
                 empsal =c(23000,45000,64000), stringsAsFactors = TRUE 
                           )
df
#View(df)
class(df)
str(df)
attributes(df)
df[,2]
df[1,]
head(mtcars)
tail(mtcars)
dim(mtcars)
nrow(mtcars)
ncol(mtcars)
data()
# ?mtcars
#View(mtcars)

[1] "integer"

[1] "numeric"

[1] "character"

[1] "logical"

[1] "complex"

[1] "character"

[1] "character"

[1] "character"

[1] "character"

[1] "numeric"

[1] 7

[1] "90"

[1] "TRUE" "5"    "65"   "yes"

[1] "5"  "65"

[1] "5"  "90" "65"

[1] "TRUE" "yes"

[1] "TRUE" "yes"

[1] "TRUE" "678"  "90"   "45"   "yes"

[1] "integer"

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[1] 4 5 6 7 8 9

[1] 4 9

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[1] 5

Warning message in myVec == c(12, 56):
“longer object length is not a multiple of shorter object length”

[1] 12

[1]  1  2  3  4  5 NA NA NA NA NA NA NA

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 3 4

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


[1]  2  5  8 11

[,1] [,2] [,3]
[1,] 4    7    10  
[2,] 5    8    11  
[3,] 6    9    12

[,1] [,2]
[1,] 7    7   
[2,] 8    8   
[3,] 9    9

[,1] [,2]
[1,] 7    7   
[2,] 8    8   
[3,] 9    9

[1] 5

[1] 5

[,1] [,2] [,3] [,4]
[1,] 3    6    9    12  
[2,] 3    6    9    12

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12



[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

[1] 5 6 7 8

[1] 5

[1] 23 45

empno empname empsal
1  23   ramesh  23000 
2 -92   rajesh  45000 
3  50   suresh  64000

[1] "data.frame"

'data.frame':	3 obs. of  3 variables:
 $ empno  : int  23 -92 50
 $ empname: Factor w/ 3 levels "rajesh","ramesh",..: 2 1 3
 $ empsal : num  23000 45000 64000


$names
[1] "empno"   "empname" "empsal" 

$row.names
[1] 1 2 3

$class
[1] "data.frame"

[1] ramesh rajesh suresh
Levels: rajesh ramesh suresh

empno empname empsal
1 23    ramesh  23000

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

mpg  cyl disp  hp  drat wt    qsec vs am gear carb
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.7 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.9 1  1  5    2   
Ford Pantera L 15.8 8   351.0 264 4.22 3.170 14.5 0  1  5    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.5 0  1  5    6   
Maserati Bora  15.0 8   301.0 335 3.54 3.570 14.6 0  1  5    8   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.6 1  1  4    2

[1] 32 11

[1] 32

[1] 11

In [3]:
#lists
mylist <- list (a = 1:5, b = "Hi There", c = function(x) x * sin(x))

In [2]:
mylist[1]

$a
[1] 1 2 3 4 5

In [3]:
#mylist[1] + 1      # Can we do math on that?

ERROR: Error in mylist[1] + 1: non-numeric argument to binary operator


In [4]:
mylist[[1]]

[1] 1 2 3 4 5

In [5]:
mylist$a

[1] 1 2 3 4 5

In [6]:
mylist$a + 1      # Can we do math on that?
# Answer: yes.

[1] 2 3 4 5 6

In [7]:
mylist$a[2]       # What's the second element of the item named "a"?
# Answer: 2.

[1] 2

In [8]:
mylist$a[-2]      # Give me everything from "a" except the second element
# Remember the negative subscript?

[1] 1 3 4 5

In [ ]:
# Adding items to, and deleting items from, a list

In [9]:
mylist                     # Here's what mylist looks like right now

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)

In [10]:
mylist$d <- "New item"     # Add a new item and print out the list

In [11]:
mylist                     # We could have assigned to mylist[[4]]; then that
length(mylist)             # The length of a list is the number of elements

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)

$d
[1] "New item"

In [13]:
mylist$b <- NULL           # Delete item b and print out the list

In [2]:
mylist

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)

In [3]:
print(mylist)

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)



In [2]:
print(mylist[[2]])

[1] "Hi There"


In [5]:
print(mylist[[c(3)]])

function(x) x * sin(x)


In [7]:
print(mylist[[c(1,3)]])

[1] 3


In [8]:
print(mylist[c(1,3)])

$a
[1] 1 2 3 4 5

$c
function (x) 
x * sin(x)



In [1]:
mtcarsN <- read.csv("data/mtcars.csv")

In [2]:
head(mtcarsN)

X                 mpg  cyl disp hp  drat wt    qsec  vs am gear carb
1 Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
2 Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
3 Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
4 Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
5 Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
6 Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [6]:
getwd()
# setwd("C:/Users/lucid it training/Desktop/first")

# ?print # to take help from r documentation
print("welcome to data science course") # to print something to console
a <- 123
print(a)
# calculator 
12 +23
90-34
print(1:50)
ab <- 50:100
ab
ab[ab == 76]
#?which
which(ab == 76) # to get the location index of perticular value

myObj <- c(23,45,78,98,123)
length(myObj)#how many values presented
class(myObj)
myObj1 <- c("hello", "world")
class(myObj1)
print('hello world')

myObjInt <- c(23L,45L,78L,98L,123L)
myObjInt <- c(23L,45L,78L,98L,123)
class(myObjInt)
myObjComp <- c(1+2i, 7+8i, -9-45i,-3+23i)
class(myObjComp)
myObjLog <- c(TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE)
class(myObjLog)
#### indexing/slicing
myObjLog[3]+myObjLog[7]
myobjUN <- c(1,0,1,1,0)
class(myobjUN)
T
F
T+T
myobjUN <- c(T,F,T,T,F)
class(myobjUN)
myObjComp
#myObjComp[1,3,4]
myObjComp[c(1,3,4)]
myObjComp[-2]
myObjComp[c(-2)]
myObjComp[c(-2,-4)]
fh <- 50:100
fh[20:38]
#fh[(-20:-38)]
fh[-c(20:38)]
-9:-1

# which(fh==c(56,  90, 96, 99)) ####
# ?which

pi
class(pi)
letters
LETTERS
class(letters)
month.name
month.abb
month.abb <- "sumendar"
# month.abb
# rm(month.abb)
# month.abb

[1] "/home/nbuser/library/1-DataTypesAndDataStructures"

[1] "welcome to data science course"
[1] 123


[1] 35

[1] 56

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50


[1]  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
[20]  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
[39]  88  89  90  91  92  93  94  95  96  97  98  99 100

[1] 76

[1] 27

[1] 5

[1] "numeric"

[1] "character"

[1] "hello world"


[1] "numeric"

[1] "complex"

[1] "logical"

[1] 2

[1] "numeric"

[1] TRUE

[1] FALSE

[1] 2

[1] "logical"

[1]  1+ 2i  7+ 8i -9-45i -3+23i

[1]  1+ 2i -9-45i -3+23i

[1]  1+ 2i -9-45i -3+23i

[1]  1+ 2i -9-45i -3+23i

[1]  1+ 2i -9-45i

[1] 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87

[1]  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
[20]  88  89  90  91  92  93  94  95  96  97  98  99 100

[1] -9 -8 -7 -6 -5 -4 -3 -2 -1

[1] 3.141593

[1] "numeric"

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "character"

[1] "January"   "February"  "March"     "April"     "May"       "June"     
 [7] "July"      "August"    "September" "October"   "November"  "December"

[1] "sumendar"

In [5]:
vect <- 1:12
class(vect)
vectChar <- rep("hello", 10)
vectComp <- c(2+34i,-9-7i,6+6i)
vectNum <- c(2,34,67,78)
vectLog <- c(TRUE,FALSE,TRUE)

# 2 dimentional storage -matrix

myMat <- matrix(1:12,nrow = 3,ncol = 4)
myMat
myMatR <- matrix(1:12,nrow = 3,ncol = 4,byrow = TRUE)
myMatR
#indexing
# mat[r,c]
myMat[2,2]
myMat[3,2]
myMat[,2]#to get second column
myMat[2,] #to get second row
myMat[,c(1,3)] #to get both first and 3rd column
myMat[,-c(1,3)] #to get except first and 3rd column
myMat[-c(1,3),] #to get except first and 3rd rows
length(vect)
vect[1:5][c(TRUE,FALSE,FALSE,TRUE,FALSE)] #logical indexing
###### arrays - multi dimentional

myArr <- array(1:24,dim = c(3,4,2))
myArr
myArr[,,1]
myArr[,,2]
myArr[2,2,2]
myArr[c(2,3),2,2]
myArr[c(2,3),c(2,3),2]
###### dataframe
Name <- c("a1", "a2", "b3") # char vector
Value1 <- c(23L, 4L, 12L) # int vector
Value2 <- c(1,45,5)       # Numeric vector
value3 <- c(TRUE,FALSE,FALSE) # logical vector
## create a dataframe
dat <- data.frame(Name, Value1, Value2,value3)
dat
#View(dat)
class(myMat)
class(dat)
class(vect)
##indexing data frame
dat[1,2]
dat[c(1,2),2]
#View(dat)
dat$Name #accessing a column using name
dat$Value1 #accessing a column using name
dat[-1]
dat[,-1]
myMat[-1]
vect[-1]
dat$Value1[2]
dat$Value1[2:3]
dat$Value1[-(2:3)]
##### list  ######
lst <- list(c(2,4,5),vect,myMat,dat)
class(lst)
lst
class(lst)
lst
lst[1]
lst[[1]]
lst[[1]][2]
lst[3]
lst[3][[1]]
lst[[3]]
class(lst[3])
class(lst[[3]])
lst
lst[3]
lst
#lst2 <- list(lst2)
lst2 <- list(lst)
lst2
lst <- list(c(2,3,4),c("hello","hai"))
lst
lst[1]
lst[[1]]
lst[[2]]
lst[2][1]
lst[2][1][1]
lst
lst[[2]]
lst[2][1]
lst[2][1][1]
lst[2][1][1][1]
lst[2][[1]]
vect
names(vect) <- month.abb
vect
newVec <- c(one=1,two=2,three=3)
newVec
vect["one"]
vect["Jan"]
vect["Feb"]
vect[c("Feb","Aug","May")]
#vect[-c("Feb","Aug","May")]
vect[c(TRUE,FALSE,TRUE)]
vect*2
vect*3
which(vect=="Jul")
vect=="Jul"
vect
names(vect)=="Jul"
vect[names(vect)=="Jul"]
vect[-(names(vect)=="Jul")]

[1] "integer"

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

[1] 5

[1] 6

[1] 4 5 6

[1]  2  5  8 11

[,1] [,2]
[1,] 1    7   
[2,] 2    8   
[3,] 3    9

[,1] [,2]
[1,] 4    10  
[2,] 5    11  
[3,] 6    12

[1]  2  5  8 11

[1] 12

[1] 1 4

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4]
[1,] 13   16   19   22  
[2,] 14   17   20   23  
[3,] 15   18   21   24

[1] 17

[1] 17 18

[,1] [,2]
[1,] 17   20  
[2,] 18   21

Name Value1 Value2 value3
1 a1   23      1      TRUE 
2 a2    4     45     FALSE 
3 b3   12      5     FALSE

[1] "matrix"

[1] "data.frame"

[1] "integer"

[1] 23

[1] 23  4

[1] a1 a2 b3
Levels: a1 a2 b3

[1] 23  4 12

Value1 Value2 value3
1 23      1      TRUE 
2  4     45     FALSE 
3 12      5     FALSE

Value1 Value2 value3
1 23      1      TRUE 
2  4     45     FALSE 
3 12      5     FALSE

[1]  2  3  4  5  6  7  8  9 10 11 12

[1]  2  3  4  5  6  7  8  9 10 11 12

[1] 4

[1]  4 12

[1] 23

[1] "list"

[[1]]
[1] 2 4 5

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[4]]
  Name Value1 Value2 value3
1   a1     23      1   TRUE
2   a2      4     45  FALSE
3   b3     12      5  FALSE

[1] "list"

[[1]]
[1] 2 4 5

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[4]]
  Name Value1 Value2 value3
1   a1     23      1   TRUE
2   a2      4     45  FALSE
3   b3     12      5  FALSE

[[1]]
[1] 2 4 5

[1] 2 4 5

[1] 4

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] "list"

[1] "matrix"

[[1]]
[1] 2 4 5

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[4]]
  Name Value1 Value2 value3
1   a1     23      1   TRUE
2   a2      4     45  FALSE
3   b3     12      5  FALSE

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[1]]
[1] 2 4 5

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[4]]
  Name Value1 Value2 value3
1   a1     23      1   TRUE
2   a2      4     45  FALSE
3   b3     12      5  FALSE

[[1]]
[[1]][[1]]
[1] 2 4 5

[[1]][[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

[[1]][[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[1]][[4]]
  Name Value1 Value2 value3
1   a1     23      1   TRUE
2   a2      4     45  FALSE
3   b3     12      5  FALSE

[[1]]
[1] 2 3 4

[[2]]
[1] "hello" "hai"

[[1]]
[1] 2 3 4

[1] 2 3 4

[1] "hello" "hai"

[[1]]
[1] "hello" "hai"

[[1]]
[1] "hello" "hai"

[[1]]
[1] 2 3 4

[[2]]
[1] "hello" "hai"

[1] "hello" "hai"

[[1]]
[1] "hello" "hai"

[[1]]
[1] "hello" "hai"

[[1]]
[1] "hello" "hai"

[1] "hello" "hai"

[1]  1  2  3  4  5  6  7  8  9 10 11 12

Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec 
  1   2   3   4   5   6   7   8   9  10  11  12

one   two three 
    1     2     3

<NA> 
  NA

Jan 
  1

Feb 
  2

Feb Aug May 
  2   8   5

Jan Mar Apr Jun Jul Sep Oct Dec 
  1   3   4   6   7   9  10  12

Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec 
  2   4   6   8  10  12  14  16  18  20  22  24

Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec 
  3   6   9  12  15  18  21  24  27  30  33  36

named integer(0)

Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec 
FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec 
  1   2   3   4   5   6   7   8   9  10  11  12

[1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE

Jul 
  7

Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec 
  2   3   4   5   6   7   8   9  10  11  12

[1]  0  0  0  0  0  0 -1  0  0  0  0  0