# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Data-types-&amp;-Data-structures" data-toc-modified-id="Data-types-&amp;-Data-structures-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data types &amp; Data structures</a></div><div class="lev2 toc-item"><a href="#Primary-data-structures" data-toc-modified-id="Primary-data-structures-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Primary data structures</a></div><div class="lev3 toc-item"><a href="#Vectors-(atomic-vectors)" data-toc-modified-id="Vectors-(atomic-vectors)-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Vectors (atomic vectors)</a></div><div class="lev2 toc-item"><a href="#Types-of-atomic-Vectors" data-toc-modified-id="Types-of-atomic-Vectors-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Types of atomic Vectors</a></div><div class="lev3 toc-item"><a href="#Lists-(recursive-vectors)" data-toc-modified-id="Lists-(recursive-vectors)-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Lists (recursive vectors)</a></div><div class="lev2 toc-item"><a href="#Other-data-structures" data-toc-modified-id="Other-data-structures-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Other data structures</a></div><div class="lev3 toc-item"><a href="#matrix-and-arrays" data-toc-modified-id="matrix-and-arrays-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>matrix and arrays</a></div><div class="lev3 toc-item"><a href="#Vector-and-Matrix-Operations" data-toc-modified-id="Vector-and-Matrix-Operations-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Vector and Matrix Operations</a></div><div class="lev3 toc-item"><a href="#data-frame" data-toc-modified-id="data-frame-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>data frame</a></div><div class="lev4 toc-item"><a href="#expand.grid()" data-toc-modified-id="expand.grid()-1.3.3.1"><span class="toc-item-num">1.3.3.1&nbsp;&nbsp;</span>expand.grid()</a></div><div class="lev4 toc-item"><a href="#cbind-and-rbind" data-toc-modified-id="cbind-and-rbind-1.3.3.2"><span class="toc-item-num">1.3.3.2&nbsp;&nbsp;</span>cbind and rbind</a></div>

# Data types & Data structures

**Data structures:**  A perticular way of organizing data in a computer.  

![Imgur](https://i.imgur.com/4qUkpp6.jpg)

## Primary data structures

Vectors can be of two types:
	* Atomic vectors (basic data types in R and is pretty much the workhorse of R)
	* Recursive Vectors or lists (List is a special vector. Each element can be a different class)

### Vectors (atomic vectors)

* A vector can be a vector of characters, logical, integers or numeric.  
You can create vectors by concatenating them using the `c()` function.  
Various examples:  
`x <- c(1, 2, 3)`  
x is a numeric vector. These are the most common kind. They are numeric objects and are treated as double precision real numbers. To explicitly create integers, add a L at the end.   
`x1 <- c(1L, 2L, 3L)` 
You can also have logical vectors.  
`y <- c(TRUE, TRUE, FALSE, FALSE)`  
Finally you can have character vectors:  
`z <- c("Alec", "Dan", "Rob", "Rich")`  

```{r}
#The general pattern is vector(class of object, length). 
Create an empty vector with vector()
x <- vector()
# with a pre-defined length
x <- vector(length = 10)
# with a length and type
vector("character", length = 10)
vector("numeric", length = 10)
vector("integer", length = 10)
vector("logical", length = 10)
```

## Types of atomic Vectors

R has 5 common types of atomic vectors
	* logical (e.g., TRUE, FALSE)
	* integer (e.g,, 2L, as.integer(3))
	* numeric (real or decimal) (e.g, 2, 2.0, pi)
	* complex (e.g, 1 + 0i, 1 + 4i)
	* character (e.g, "a", "swc")

**Vectors may only have one type**   
* atomic vectors are homogeneous. This means that every element within a single atomic vector has to be of the same type
* R will create a resulting vector that is the least common denominator. The coercion will move towards the one that's easiest to coerce to.
Guess what the following do without running them first    
```{r}
xx <- c(1.7, "a")
xx <- c(TRUE, 2)
xx <- c("a", TRUE)
This is called implicit coercion.
```
The coersion rule goes   
*logical -> integer -> numeric -> complex -> character.*  

![Imgur](https://i.imgur.com/k9Ubya2.png)
   
  
```{r}
(x <- c(sort(sample(1:20, 9)), NA))
(y <- c(sort(sample(3:23, 7)), NA))
union(x, y)
intersect(x, y)
setdiff(x, y)
setdiff(y, x)
setequal(x, y)
which.min(x)
which.max(x)
match(x,y)
```
  
   
   
![Imgur](https://i.imgur.com/OhSERrh.png)

### Lists (recursive vectors)

* List is a special vector. Each element can be a different class.
* lists act as containers
* Unlike atomic vectors, its contents are not restricted to a single type
* a list can be anything, and two elements within a list can be of different types!
* Lists are sometimes called recursive vectors, because a list can contain other lists

** Create a ists using list function**      
'x <- list(1, "a", TRUE, 1+4i)'
    

## Other data structures

R also has many data structures. These include
	* matrix and arrays
    * data frame	

![Imgur](https://i.imgur.com/VgHl6y2.png?1)

![Imgur](https://i.imgur.com/c73sZAd.png?1)

### matrix and arrays

* Stacking multiple matrices
* Matrices in R can be thought of as vectors indexed using two indices instead of one

In [1]:
m <- matrix(c(47,48,52,36,89,45,1,2,-25), nrow = 3, ncol = 3)
m
# this code creates a 3 by 3 matrix

[,1] [,2] [,3]
[1,] 47   36     1 
[2,] 48   89     2 
[3,] 52   45   -25

* If a higher dimension vector is desired, then use the array() function to generate the n-dimensional object. A 3x3x3 array can be created as follows:

In [2]:
m <- array(1:27, dim=c(3,3,3))
print(m)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27



### Vector and Matrix Operations

![Imgur](https://i.imgur.com/HmnOp1F.png)
![Imgur](https://i.imgur.com/xe79KhH.png)

### data frame    

* unlike a matrix, a data frame can mix data types across columns

In [3]:
Name <- c("a1", "a2", "b3")
Value1 <- c(23, 4, 12)
Value2 <- c(1,45,5)
dat <- data.frame(Name, Value1, Value2)
dat

Name Value1 Value2
1 a1   23      1    
2 a2    4     45    
3 b3   12      5

#### expand.grid()  
(to create a data frame)
* The function `expand.grid` gives us all the combinations of entries of two vectors.

For example:  
all combinations of `blue and black pants` and  `white, grey and plaid shirts`

In [6]:
eg <- expand.grid(pants = c("blue", "black"), shirt = c("white", "grey", "plaid"))
class(eg)

[1] "data.frame"

In [8]:
#generate a deck of cards
suits <- c("Diamonds", "Clubs", "Hearts", "Spades")
numbers <- c("Ace", "Deuce", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Jack", "Queen", "King")
deck <- expand.grid(number=numbers, suit=suits)
class(deck)
print(deck)
deck <- paste(deck$number, deck$suit)
class(deck)
print(deck)

[1] "data.frame"

   number     suit
1     Ace Diamonds
2   Deuce Diamonds
3   Three Diamonds
4    Four Diamonds
5    Five Diamonds
6     Six Diamonds
7   Seven Diamonds
8   Eight Diamonds
9    Nine Diamonds
10    Ten Diamonds
11   Jack Diamonds
12  Queen Diamonds
13   King Diamonds
14    Ace    Clubs
15  Deuce    Clubs
16  Three    Clubs
17   Four    Clubs
18   Five    Clubs
19    Six    Clubs
20  Seven    Clubs
21  Eight    Clubs
22   Nine    Clubs
23    Ten    Clubs
24   Jack    Clubs
25  Queen    Clubs
26   King    Clubs
27    Ace   Hearts
28  Deuce   Hearts
29  Three   Hearts
30   Four   Hearts
31   Five   Hearts
32    Six   Hearts
33  Seven   Hearts
34  Eight   Hearts
35   Nine   Hearts
36    Ten   Hearts
37   Jack   Hearts
38  Queen   Hearts
39   King   Hearts
40    Ace   Spades
41  Deuce   Spades
42  Three   Spades
43   Four   Spades
44   Five   Spades
45    Six   Spades
46  Seven   Spades
47  Eight   Spades
48   Nine   Spades
49    Ten   Spades
50   Jack   Spades
51  Queen   Spades
52   King   

[1] "character"

 [1] "Ace Diamonds"   "Deuce Diamonds" "Three Diamonds" "Four Diamonds" 
 [5] "Five Diamonds"  "Six Diamonds"   "Seven Diamonds" "Eight Diamonds"
 [9] "Nine Diamonds"  "Ten Diamonds"   "Jack Diamonds"  "Queen Diamonds"
[13] "King Diamonds"  "Ace Clubs"      "Deuce Clubs"    "Three Clubs"   
[17] "Four Clubs"     "Five Clubs"     "Six Clubs"      "Seven Clubs"   
[21] "Eight Clubs"    "Nine Clubs"     "Ten Clubs"      "Jack Clubs"    
[25] "Queen Clubs"    "King Clubs"     "Ace Hearts"     "Deuce Hearts"  
[29] "Three Hearts"   "Four Hearts"    "Five Hearts"    "Six Hearts"    
[33] "Seven Hearts"   "Eight Hearts"   "Nine Hearts"    "Ten Hearts"    
[37] "Jack Hearts"    "Queen Hearts"   "King Hearts"    "Ace Spades"    
[41] "Deuce Spades"   "Three Spades"   "Four Spades"    "Five Spades"   
[45] "Six Spades"     "Seven Spades"   "Eight Spades"   "Nine Spades"   
[49] "Ten Spades"     "Jack Spades"    "Queen Spades"   "King Spades"   


#### cbind and rbind
(to create a data frame)
`cbind`	Building a Matrix from Columns or Rows  


In [11]:
df <- data.frame(x = 1:3, y = c("a", "b", "c"))
df
cbind(1,  df) 

x y
1 1 a
2 2 b
3 3 c

1 x y
1 1 1 a
2 1 2 b
3 1 3 c

In [13]:
# 3 column matrix with column dimnames
cbind(Index = c(1:3), Age = c(30, 45, 34), Salary = c(500, 600, 550)) 

Index Age Salary
[1,] 1     30  500   
[2,] 2     45  600   
[3,] 3     34  550

In [18]:
df <- data.frame(a = c(1:5), b = (1:5)^2)
df
rbind(df, c(2, 3), c(5, 6))

a b 
1 1  1
2 2  4
3 3  9
4 4 16
5 5 25

a b 
1 1  1
2 2  4
3 3  9
4 4 16
5 5 25
6 2  3
7 5  6