# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Data-types-&amp;-Data-structures" data-toc-modified-id="Data-types-&amp;-Data-structures-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data types &amp; Data structures</a></div><div class="lev2 toc-item"><a href="#Primary-data-structures" data-toc-modified-id="Primary-data-structures-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Primary data structures</a></div><div class="lev3 toc-item"><a href="#Vectors-(atomic-vectors)" data-toc-modified-id="Vectors-(atomic-vectors)-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Vectors (atomic vectors)</a></div><div class="lev2 toc-item"><a href="#Types-of-atomic-Vectors" data-toc-modified-id="Types-of-atomic-Vectors-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Types of atomic Vectors</a></div><div class="lev3 toc-item"><a href="#Lists-(recursive-vectors)" data-toc-modified-id="Lists-(recursive-vectors)-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Lists (recursive vectors)</a></div><div class="lev2 toc-item"><a href="#Other-data-structures" data-toc-modified-id="Other-data-structures-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Other data structures</a></div><div class="lev3 toc-item"><a href="#matrix-and-arrays" data-toc-modified-id="matrix-and-arrays-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>matrix and arrays</a></div><div class="lev3 toc-item"><a href="#data-frame" data-toc-modified-id="data-frame-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>data frame</a></div><div class="lev4 toc-item"><a href="#expand.grid()" data-toc-modified-id="expand.grid()-1.3.2.1"><span class="toc-item-num">1.3.2.1&nbsp;&nbsp;</span>expand.grid()</a></div><div class="lev4 toc-item"><a href="#cbind-and-rbind" data-toc-modified-id="cbind-and-rbind-1.3.2.2"><span class="toc-item-num">1.3.2.2&nbsp;&nbsp;</span>cbind and rbind</a></div>

# Data types & Data structures

**Data structures:**  A perticular way of organizing data in a computer.  

![Imgur](https://i.imgur.com/SXhHlye.jpg)

## Primary data structures

Vectors can be of two types:
	* Atomic vectors (basic data types in R and is pretty much the workhorse of R)
	* Recursive Vectors or lists (List is a special vector. Each element can be a different class)

### Vectors (atomic vectors)

* A vector can be a vector of characters, logical, integers or numeric.  
You can create vectors by concatenating them using the `c()` function.  
Various examples:  
`x <- c(1, 2, 3)`  
x is a numeric vector. These are the most common kind. They are numeric objects and are treated as double precision real numbers. To explicitly create integers, add a L at the end.   
`x1 <- c(1L, 2L, 3L)` 
You can also have logical vectors.  
`y <- c(TRUE, TRUE, FALSE, FALSE)`  
Finally you can have character vectors:  
`z <- c("Alec", "Dan", "Rob", "Rich")`  

```{r}
#The general pattern is vector(class of object, length). 
Create an empty vector with vector()
x <- vector()
# with a pre-defined length
x <- vector(length = 10)
# with a length and type
vector("character", length = 10)
vector("numeric", length = 10)
vector("integer", length = 10)
vector("logical", length = 10)
```

## Types of atomic Vectors

R has 5 common types of atomic vectors
	* logical (e.g., TRUE, FALSE)
	* integer (e.g,, 2L, as.integer(3))
	* numeric (real or decimal) (e.g, 2, 2.0, pi)
	* complex (e.g, 1 + 0i, 1 + 4i)
	* character (e.g, "a", "swc")

**Vectors may only have one type**   
* atomic vectors are homogeneous. This means that every element within a single atomic vector has to be of the same type
* R will create a resulting vector that is the least common denominator. The coercion will move towards the one that's easiest to coerce to.
Guess what the following do without running them first    
```{r}
xx <- c(1.7, "a")
xx <- c(TRUE, 2)
xx <- c("a", TRUE)
This is called implicit coercion.
```
The coersion rule goes   
*logical -> integer -> numeric -> complex -> character.*  

![Imgur](https://i.imgur.com/k9Ubya2.png)
   
  
```{r}
(x <- c(sort(sample(1:20, 9)), NA))
(y <- c(sort(sample(3:23, 7)), NA))
rev(x)
union(x, y)
intersect(x, y)
setdiff(x, y)
setdiff(y, x)
setequal(x, y)
```

### Lists (recursive vectors)

* List is a special vector. Each element can be a different class.
* lists act as containers
* Unlike atomic vectors, its contents are not restricted to a single type
* a list can be anything, and two elements within a list can be of different types!
* Lists are sometimes called recursive vectors, because a list can contain other lists

** Create a ists using list function**      
'x <- list(1, "a", TRUE, 1+4i)'
    

## Other data structures

R also has many data structures. These include
	* matrix and arrays
    * data frame	

![Imgur](https://i.imgur.com/VgHl6y2.png?1)

![Imgur](https://i.imgur.com/c73sZAd.png?1)

### matrix and arrays

* Stacking multiple matrices
* Matrices in R can be thought of as vectors indexed using two indices instead of one

In [1]:
m <- matrix(c(47,48,52,36,89,45,1,2,-25), nrow = 3, ncol = 3)
m
# this code creates a 3 by 3 matrix

[,1] [,2] [,3]
[1,] 47   36     1 
[2,] 48   89     2 
[3,] 52   45   -25

* If a higher dimension vector is desired, then use the array() function to generate the n-dimensional object. A 3x3x3 array can be created as follows:

In [2]:
m <- array(1:27, dim=c(3,3,3))
print(m)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27



### data frame    

* unlike a matrix, a data frame can mix data types across columns

In [3]:
Name <- c("a1", "a2", "b3")
Value1 <- c(23, 4, 12)
Value2 <- c(1,45,5)
dat <- data.frame(Name, Value1, Value2)
dat

Name Value1 Value2
1 a1   23      1    
2 a2    4     45    
3 b3   12      5

#### expand.grid()  
(to create a data frame)

#### cbind and rbind
(to create a data frame)