In [3]:
################ apply function on matrices

mnthMat <- matrix(month.name,3,4)
mnthMat
apply(mnthMat, 2, nchar) # column wise 
apply(mnthMat, 1, nchar) # row wise 

####################################### apply function on arrays
mnthArr <- array(seq(1,18),dim = c(2,3,3))
mnthArr

#rowwise operation
apply(mnthArr, 1, mean) 
# is nothing but
mean(c(1,3,5,7,9,11,13,15,17))
# or 
mean(c(mnthArr[,,1][1,],mnthArr[,,2][1,],mnthArr[,,3][1,]))

#column wise operation
apply(mnthArr, 2, mean) 
# is nothing but
mean(c(1,2,7,8,13,14))
# or 
mean(c(mnthArr[,,1][,1],mnthArr[,,2][,1],mnthArr[,,3][,1]))

#table wise operation
apply(mnthArr, 3, mean)
# is nothing but
mean(1:6)
# or 
mean(mnthArr[,,1])

############################################
############### 
lapply(month.name, nchar)
sapply(month.name, nchar)
#############
str(iris)
print(tapply(iris$Sepal.Length, iris$Species, mean))
print(tapply(mtcars$mpg, mtcars$cyl, mean))
print(tapply(mtcars$mpg, mtcars$carb, mean))
print(tapply(mtcars$mpg, mtcars$gear, mean))

aggregate(iris[-5], list(iris$Species), mean)
aggregate(iris[1:4], list(iris$Species), mean)
aggregate(iris[,1:4], list(iris$Species), mean)

## Formulas, one ~ one, one ~ many, many ~ one, and many ~ many:
aggregate(weight ~ feed, data = chickwts, mean)
aggregate(breaks ~ wool + tension, data = warpbreaks, mean)
aggregate(cbind(Ozone, Temp) ~ Month, data = airquality, mean)
aggregate(cbind(ncases, ncontrols) ~ alcgp + tobgp, data = esoph, sum)

## Dot notation:
aggregate(. ~ Species, data = iris, mean)
aggregate(len ~ ., data = ToothGrowth, mean)

###### mapply
l1 <- list(a = c(1:10), b = c(11:20))
l2 <- list(c = c(21:30), d = c(31:40))
l1
l2
print(mapply(sum, l1$a, l1$b, l2$c, l2$d))
sum(c(1,11,21,31))
print(mapply(sum, l1))
sum(1:10)
sum(11:20)
print(mapply(sum, l1,l2))

########## by function

b <- by(iris[, 1:4], iris$Species, colMeans)
b

####################### with()

mtcars$mpg[mtcars$cyl == 8  &  mtcars$disp > 350]
with(mtcars, mpg[cyl == 8  &  disp > 350]) # we can avoid using $ notation by with() function

############## attach()

x <- data.frame(Subtype= c("A","A","B","A","B","B","A","B","A","B"), 
                Gender= rep(c("m","f"),each=5), 
                Expression = c(-0.54,-0.8,-1.03,-0.41,-1.31,-0.66,-0.43,1.01,-1.15,0.14))

x
x$Expression
# Expression  # you will get an error
attach(x) #using attach
Expression  # you will get answer
detach(x)
# Expression  # error
x$Expression

[,1]     [,2]  [,3]      [,4]    
[1,] January  April July      October 
[2,] February May   August    November
[3,] March    June  September December

[,1] [,2] [,3] [,4]
[1,] 7    5    4    7   
[2,] 8    3    6    8   
[3,] 5    4    9    8

[,1] [,2] [,3]
[1,] 7    8    5   
[2,] 5    3    4   
[3,] 4    6    9   
[4,] 7    8    8

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

[1]  9 10

[1] 9

[1] 9

[1]  7.5  9.5 11.5

[1] 7.5

[1] 7.5

[1]  3.5  9.5 15.5

[1] 3.5

[1] 3.5

[[1]]
[1] 7

[[2]]
[1] 8

[[3]]
[1] 5

[[4]]
[1] 5

[[5]]
[1] 3

[[6]]
[1] 4

[[7]]
[1] 4

[[8]]
[1] 6

[[9]]
[1] 9

[[10]]
[1] 7

[[11]]
[1] 8

[[12]]
[1] 8

January  February     March     April       May      June      July    August 
        7         8         5         5         3         4         4         6 
September   October  November  December 
        9         7         8         8

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
    setosa versicolor  virginica 
     5.006      5.936      6.588 
       4        6        8 
26.66364 19.74286 15.10000 
       1        2        3        4        6        8 
25.34286 22.40000 16.30000 15.79000 19.70000 15.00000 
       3        4        5 
16.10667 24.53333 21.38000 


Group.1    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

Group.1    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

Group.1    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

feed      weight  
1 casein    323.5833
2 horsebean 160.2000
3 linseed   218.7500
4 meatmeal  276.9091
5 soybean   246.4286
6 sunflower 328.9167

wool tension breaks  
1 A    L       44.55556
2 B    L       28.22222
3 A    M       24.00000
4 B    M       28.77778
5 A    H       24.55556
6 B    H       18.77778

Month Ozone    Temp    
1 5     23.61538 66.73077
2 6     29.44444 78.22222
3 7     59.11538 83.88462
4 8     59.96154 83.96154
5 9     31.44828 76.89655

alcgp     tobgp    ncases ncontrols
1  0-39g/day 0-9g/day  9     261      
2  40-79     0-9g/day 34     179      
3  80-119    0-9g/day 19      61      
4  120+      0-9g/day 16      24      
5  0-39g/day 10-19    10      84      
6  40-79     10-19    17      85      
7  80-119    10-19    19      49      
8  120+      10-19    12      18      
9  0-39g/day 20-29     5      42      
10 40-79     20-29    15      62      
11 80-119    20-29     6      16      
12 120+      20-29     7      12      
13 0-39g/day 30+       5      28      
14 40-79     30+       9      29      
15 80-119    30+       7      12      
16 120+      30+      10      13

Species    Sepal.Length Sepal.Width Petal.Length Petal.Width
1 setosa     5.006        3.428       1.462        0.246      
2 versicolor 5.936        2.770       4.260        1.326      
3 virginica  6.588        2.974       5.552        2.026

supp dose len  
1 OJ   0.5  13.23
2 VC   0.5   7.98
3 OJ   1.0  22.70
4 VC   1.0  16.77
5 OJ   2.0  26.06
6 VC   2.0  26.14

$a
 [1]  1  2  3  4  5  6  7  8  9 10

$b
 [1] 11 12 13 14 15 16 17 18 19 20

$c
 [1] 21 22 23 24 25 26 27 28 29 30

$d
 [1] 31 32 33 34 35 36 37 38 39 40

 [1]  64  68  72  76  80  84  88  92  96 100


[1] 64

  a   b 
 55 155 


[1] 55

[1] 155

  a   b 
310 510 


iris$Species: setosa
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       5.006        3.428        1.462        0.246 
------------------------------------------------------------ 
iris$Species: versicolor
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       5.936        2.770        4.260        1.326 
------------------------------------------------------------ 
iris$Species: virginica
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       6.588        2.974        5.552        2.026 

[1] 18.7 14.3 10.4 10.4 14.7 19.2 15.8

[1] 18.7 14.3 10.4 10.4 14.7 19.2 15.8

Subtype Gender Expression
1  A       m      -0.54     
2  A       m      -0.80     
3  B       m      -1.03     
4  A       m      -0.41     
5  B       m      -1.31     
6  B       f      -0.66     
7  A       f      -0.43     
8  B       f       1.01     
9  A       f      -1.15     
10 B       f       0.14

[1] -0.54 -0.80 -1.03 -0.41 -1.31 -0.66 -0.43  1.01 -1.15  0.14

[1] -0.54 -0.80 -1.03 -0.41 -1.31 -0.66 -0.43  1.01 -1.15  0.14

[1] -0.54 -0.80 -1.03 -0.41 -1.31 -0.66 -0.43  1.01 -1.15  0.14

In [2]:
# setwd("C:/Users/user/Downloads/DSwRandP-apr18-master/DSwRandP-apr18-master/FunctionsAndApplyFamily")
sum(1,2) # inbuilt function to add elements
# sum1(1,2) # 
# to create a function
sum1 <- function(x,y) {
  x+y
}
sum <- c(1,2)
class(sum)
letters <- c(1,2)
letters

rm(letters)
obj <- letters
obj
letters
sum(1,2)
sum1(1,2)

abs(-3)
abs(-1.3)
sqrt(64)	# square root function
8^2 # exponential
round(3.455) # nearest integer value
round(3.955)
ceiling(3.475)	
floor(3.475)	

ceiling(3.175)#lookin at top	
round(3.175)	
floor(3.475)	#looking at bottom
floor(3.9999999)	#looking at bottom
round(3.9999999)
trunc(5.99)
log(1)
log2(16)
log(2.71828)
# e =2.71828
toupper("sumendar")
tolower("SUMENDAR")

[1] 3

[1] "numeric"

[1] 1 2

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] 3

[1] 3

[1] 3

[1] 1.3

[1] 8

[1] 64

[1] 3

[1] 4

[1] 4

[1] 3

[1] 4

[1] 3

[1] 3

[1] 3

[1] 4

[1] 5

[1] 0

[1] 4

[1] 0.9999993

[1] "SUMENDAR"

[1] "sumendar"

In [9]:
#functions

sum1(2,3)


sum1(56,78)
# without arguments
display <- function()
{
  print("lucid it solutions")
}
display()

# function define
sum_of_squares <- function(x,y) {  
  x^2 + y^2
}
sum_of_squares(3,4) # function call
#example
# function to print x raised to the power y

pow <- function(x, y) {
  result <- x^y
  print(paste(x,"raised to the power", y, "is", result))
}
pow(2,3)
#Default Arguments
# Create a function with arguments.
new.function <- function(a = 3, b = 6) {
  result <- a * b
  #print(result)
  return(result) # to print to the console
}


new.function <- function(a=5, b) {
  result <- a * b
  #print(result)
  return(result) # to print to the console
}
#new.function(,3)  #this will take the value 3 for b  


#new.function() # this will print default values result
new.function(2,3) # 
#new.function(2)
#new.function(,2)


add <- function(x,y=1,z=2){
  x+y
  x+z

}
add(5)

add <- function(x,y=1,z=2){
  x+y
  x+z
  return(c(x+y,x+z))  
}
add(5)



add <- function(x,y=1,z=2){
  x+y
  x+z
  return(paste(x+y,x+z))  
}
add(5)


add <- function(x,y=1,z=2){
  x+y
  x+z
  print(paste(x+y,x+z))  
}
add(5)

fahr_to_kelvin <- function(temp) {
  kelvin <- ((temp - 32) * (5 / 9)) + 273.15
  return(kelvin)
}

fahr_to_kelvin(35)
# Named Arguments¶

pow(8, 2)
pow(x = 8, y = 2)
pow(y = 2, x = 8)
pow(2, x = 8)
pow(2, y = 8)
class(substring(pow(sum(1,2),5), 3,8)) # functions with in another function
# Lazy evaluation

fun <- function(a,b){
  a^2
}

fun(2,x/0)

fun <- function(a,b){
  b^2
}

fun(2,x/0)

fun <- function(a,b){
  b^2
}

fun(2,3/0)
x <- 5
fun(2,x/1)
# Lazy evaluation of args

fun <- function(x){
  10
}
fun("hello")
#functions without name
(function(x) x*10)(5)


x <- 5 # global assignment of x is not used by the fun
fun <- function(x){
  #parameter x is passed by value (copy)
  x <- x+1 # local variable is modified
  print(x)
}
fun(1) # prints 
#fun() # prints 


input_1 = 20
mySum <- function(input_1, input_2 = 10) {
  output <- input_1 + input_2
  return(output)
}
mySum(input_1 = 1, 3)
mySum(input_1 = 1, 3)



input_1 = 20
mySum <- function(input_1a=input_1, input_2 = 10) {
  output <- input_1a + input_2
  return(output)
}

mySum()

[1] 5

[1] 134

[1] "lucid it solutions"


[1] 25

[1] "2 raised to the power 3 is 8"


[1] 6

[1] 7

[1] 6 7

[1] "6 7"

[1] "6 7"


[1] 274.8167

[1] "8 raised to the power 2 is 64"
[1] "8 raised to the power 2 is 64"
[1] "8 raised to the power 2 is 64"
[1] "8 raised to the power 2 is 64"
[1] "2 raised to the power 8 is 256"
[1] "3 raised to the power 5 is 243"


[1] "character"

[1] 4

[1] Inf

[1] Inf

[1] 25

[1] 10

[1] 50

[1] 2


[1] 4

[1] 4

[1] 30

In [1]:
sum(3,4)
prod(3,4)
sum(3,4) + prod(3,4)
sum(8,4) + prod(8,4)
sum(9,4) + prod(9,4)
sum(5,3) + prod(5,3)

sumprod <- function(x,y){ # 
  sum(x,y) + prod(x,y)
}

sumprod(8,4) #invoking

x <- seq(2,14)
y <- x+1
sumprod(x,y) #invoking the function using x and y vectors
options(scipen = 999) # to print exponential values as normal values
sumprod(x,y)

tu<- toupper("lucid it solutions") # to become uppercase
tolower(tu)  # to print as lower case
substring("lucid it solutions", 3,5)
substring("lucid it solutions", 5,8)


sumprod <- function(x,y){ # 
  sum(x,y)
  sum(x,y) + prod(x,y) #last statement result only invoked
}

sumprod(8,4) #invoking
sum(8,4)



sumprod <- function(x,y){ # 
  return(sum(x,y)) # this statement will execute last
  sum(x,y) + prod(x,y) 
}
sumprod(8,4) #invoking

sumprod <- function(x,y){ # 
  return(sum(x,y)) # this statement will execute last
  return(sum(x,y) + prod(x,y)) 
}
sumprod(8,4) #invoking


sumprod <- function(x,y){ # 
  return(c(sum(x,y), (sum(x,y) + prod(x,y)), "hello")) # return argument should only one
}
sumprod(8,4) #invoking

########## default arguments

new.function <- function(a = 3, b = 6) {  # givilng arguement values as default
  result <- a * b
  print(result)
}
new.function() # invoking without arguements
new.function(5) # invoking with single arguement
new.function(b=5) # invoking using name
new.function(5,3) # normal 
new.function(b=4,a=2) #naming 


add <- function(x,y=1,z=2){
  x+y
  x+z
}
add(5) # last statement wiill evaluated

fahr_to_kelvin <- function(temp) {
  kelvin <- ((temp - 32) * (5 / 9)) + 273.15
  return(kelvin)
}

# functions Can be passed as arguments to other functions
substring(class(prod(sum(2,3),4)), 3,6)



### lazy evaluation
fun <- function(a,b){
  a^2
}

fun(2,x/0)
fun(2,";")

fun <- function(x){
  10
}

fun("hello")

fun <- function(x){
  paste(x,10)
}

fun("hello")

(function(x) x*10)(5)  #nameless function
  

x <- 5 # global assignment of x is not used by the fun
fun <- function(x){
  #parameter x is passed by value (copy)
  x <- x+1 # local variable is modified
  print(x)
}
fun(1) # prints 
# fun() # error


x1 <- 5 # global assignment of x is not used by the fun
fun <- function(x=x1){
  #parameter x is passed by value (copy)
  x <- x+1 # local variable is modified
  print(x)
}
fun() # result 6

[1] 7

[1] 12

[1] 19

[1] 44

[1] 49

[1] 23

[1] 44

[1] 5.700041e+22

[1] 57000408424139982897152

[1] "lucid it solutions"

[1] "cid"

[1] "d it"

[1] 44

[1] 12

[1] 12

[1] 12

[1] "12"    "44"    "hello"

[1] 18
[1] 30
[1] 15
[1] 15
[1] 8


[1] 7

[1] "meri"

[1] 4

[1] 4

[1] 10

[1] "hello 10"

[1] 50

[1] 2
[1] 6
