In [19]:
# to check current working directory
# getwd()
#setting a working directory
#setwd("E:/DSwRandP-Apr18/R-basics")
#data types

#integers
vecI<- c(1+2L)
vecI1 <- seq(2,6)
class(vecI1)


#numeric
vecN <- c(2,3,5,6)
class(vecN)
#character
vecC <- c("1+2i", "TRUE", "lucid", "23")
class(vecC)
#logical
vecL<- c(TRUE,FALSE,TRUE,FALSE)
class(vecL)
#complex
vecCom <- c(2+3i, 9-0i, -78-34i)
class(vecCom)
#data structure

#vector (1 dimentional storage of elements)
# integer vector
intVec <- c(TRUE,5L,90L,65L, "yes")
class(intVec)
numVec <- c(3,5,90,65, "lucid")
class(numVec)
charVec <- c("rajesh", "ramesh", "suresh", "90")
class(charVec)
compVec <- c(2+4i, "9+6i", -2+56i, -4-45i)
class(compVec)
logiVec <- c(12,FALSE, TRUE, TRUE)
class(logiVec)
sum(3,4)


# subsetting or indexing
intVec[3] # accessing 3rd element
intVec[-3] #ignoring only 3rd element
intVec[c(2,4)]
intVec[2:4]
intVec[-(2:4)]
intVec[-c(2:4)]
intVec[c(2,4)] <- c(678,45)
intVec

myVec <- seq(1,12)
class(myVec)
myVec
myVec[seq(4,9)]
myVec[c(4,9)]
1:12
myVec[myVec==5]
myVec <- c(12,34,56,67,83)
myVec[myVec==c(12,56)]
myVec <- seq(1,5)
myVec[1:12]
#matrix (2 dimensional storage of elemtns)
myMat <- matrix(1:12, 3, 4)
?matrix
myMat
dim(myMat)
# dim(myMat) <- c(1,12)
#View(myMat)
print(myMat)
# view(myMat)
# View(myMat)
# indexing of matrix
#myMat[2,3]
myMat[2,]
#myMat[,c(1,3)]
myMat[,2:4]
myMat[,rep(3,2)]
myMat[,rep(3,2)]
myMat[,seq(1,3)][2,2]
myMat[2,2]
myMat[rep(3,2),]
#arrays
myArr <- array(1:12)
dim(myArr) <- c(2,3,2)
myArr
myArr <- array(1:12,dim = c(4,3,2))
#View(myArr)
print(myArr)
# indexing of arrays
myArr[,,2]
myArr[,2,2]
myArr[1,2,2]
myArr[1,2,] <- c(23,45)
myArr[1,2,] 
myArr[1,2,] <- rep(23,2)
#data frame
# creating data frame
df <- data.frame(empno=c(23L,-92L,50L),
                 empname=c("ramesh", "rajesh", "suresh"),
                 empsal =c(23000,45000,64000), stringsAsFactors = TRUE 
                           )
df
#View(df)
class(df)
str(df)
attributes(df)
df[,2]
df[1,]
head(mtcars)
tail(mtcars)
dim(mtcars)
nrow(mtcars)
ncol(mtcars)
data()
# ?mtcars
#View(mtcars)

[1] "integer"

[1] "numeric"

[1] "character"

[1] "logical"

[1] "complex"

[1] "character"

[1] "character"

[1] "character"

[1] "character"

[1] "numeric"

[1] 7

[1] "90"

[1] "TRUE" "5"    "65"   "yes"

[1] "5"  "65"

[1] "5"  "90" "65"

[1] "TRUE" "yes"

[1] "TRUE" "yes"

[1] "TRUE" "678"  "90"   "45"   "yes"

[1] "integer"

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[1] 4 5 6 7 8 9

[1] 4 9

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[1] 5

Warning message in myVec == c(12, 56):
“longer object length is not a multiple of shorter object length”

[1] 12

[1]  1  2  3  4  5 NA NA NA NA NA NA NA

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 3 4

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


[1]  2  5  8 11

[,1] [,2] [,3]
[1,] 4    7    10  
[2,] 5    8    11  
[3,] 6    9    12

[,1] [,2]
[1,] 7    7   
[2,] 8    8   
[3,] 9    9

[,1] [,2]
[1,] 7    7   
[2,] 8    8   
[3,] 9    9

[1] 5

[1] 5

[,1] [,2] [,3] [,4]
[1,] 3    6    9    12  
[2,] 3    6    9    12

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12



[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

[1] 5 6 7 8

[1] 5

[1] 23 45

empno empname empsal
1  23   ramesh  23000 
2 -92   rajesh  45000 
3  50   suresh  64000

[1] "data.frame"

'data.frame':	3 obs. of  3 variables:
 $ empno  : int  23 -92 50
 $ empname: Factor w/ 3 levels "rajesh","ramesh",..: 2 1 3
 $ empsal : num  23000 45000 64000


$names
[1] "empno"   "empname" "empsal" 

$row.names
[1] 1 2 3

$class
[1] "data.frame"

[1] ramesh rajesh suresh
Levels: rajesh ramesh suresh

empno empname empsal
1 23    ramesh  23000

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

mpg  cyl disp  hp  drat wt    qsec vs am gear carb
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.7 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.9 1  1  5    2   
Ford Pantera L 15.8 8   351.0 264 4.22 3.170 14.5 0  1  5    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.5 0  1  5    6   
Maserati Bora  15.0 8   301.0 335 3.54 3.570 14.6 0  1  5    8   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.6 1  1  4    2

[1] 32 11

[1] 32

[1] 11

In [3]:
#lists
mylist <- list (a = 1:5, b = "Hi There", c = function(x) x * sin(x))

In [2]:
mylist[1]

$a
[1] 1 2 3 4 5

In [3]:
#mylist[1] + 1      # Can we do math on that?

ERROR: Error in mylist[1] + 1: non-numeric argument to binary operator


In [4]:
mylist[[1]]

[1] 1 2 3 4 5

In [5]:
mylist$a

[1] 1 2 3 4 5

In [6]:
mylist$a + 1      # Can we do math on that?
# Answer: yes.

[1] 2 3 4 5 6

In [7]:
mylist$a[2]       # What's the second element of the item named "a"?
# Answer: 2.

[1] 2

In [8]:
mylist$a[-2]      # Give me everything from "a" except the second element
# Remember the negative subscript?

[1] 1 3 4 5

In [ ]:
# Adding items to, and deleting items from, a list

In [9]:
mylist                     # Here's what mylist looks like right now

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)

In [10]:
mylist$d <- "New item"     # Add a new item and print out the list

In [11]:
mylist                     # We could have assigned to mylist[[4]]; then that
length(mylist)             # The length of a list is the number of elements

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)

$d
[1] "New item"

In [13]:
mylist$b <- NULL           # Delete item b and print out the list

In [2]:
mylist

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)

In [3]:
print(mylist)

$a
[1] 1 2 3 4 5

$b
[1] "Hi There"

$c
function (x) 
x * sin(x)



In [2]:
print(mylist[[2]])

[1] "Hi There"


In [5]:
print(mylist[[c(3)]])

function(x) x * sin(x)


In [7]:
print(mylist[[c(1,3)]])

[1] 3


In [8]:
print(mylist[c(1,3)])

$a
[1] 1 2 3 4 5

$c
function (x) 
x * sin(x)



In [1]:
mtcarsN <- read.csv("data/mtcars.csv")

In [2]:
head(mtcarsN)

X                 mpg  cyl disp hp  drat wt    qsec  vs am gear carb
1 Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
2 Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
3 Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
4 Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
5 Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
6 Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1